** Gruppen:
1: jüdisch / no ongoing suffering
2: jüdisch / ongoing suffering
3: nicht jüdisch / no ongoing suffering
4: nicht jüdisch / ongoing suffering


<expt >
/ onexptbegin = [values.group = random(1,2,3,4)]
/ blocks = [	1 = intro;
				2 = facial_davids;
				3 = suspicion1;
				4 = mc_open;
				5 = david_fragen;
				6 = mc;
				7 = demog;
				8 = as;
				9 = nachbefragung]
</expt>


<values>
/group = 0
</values>

<data>
/ columns = [date, time, subject, values.group, blockcode, blocknum, trialcode, trialnum, response, correct, latency, stimulusnumber, stimulusitem, stimulusnumber, stimulusitem, stimulusnumber, stimulusitem]
</data>

<defaults>
/ screencolor = (255, 255, 255)
/ txbgcolor = (255, 255, 255)
/ fontstyle = ("Arial", 3%, false, false, false, false, 5, 0)
/ endlock = true("Vielen Dank für Ihre Teilnahme!") 
/ valign = center
/ halign =center
</defaults>

<instruct>
/ inputdevice = mouse
/ nextlabel = "Weiter"
/ lastlabel = "Weiter"
/ fontstyle = ("Arial", 2%)
/ windowsize=(98%,95%)
</instruct>

*********************INTRO**********************
***************************************************

<picture logo>
/ items = ("humfak_leiste.jpg")
/ position = (50,10)
</picture>

<text introtext1>
/ fontstyle = ("Arial", 3%, false, false, true)
/ items = ("S O C I A L     C O G N I T I O N     C O L O G N E")
/ position = (50, 20)
</text>

<text introtext2>
/ fontstyle = ("Arial", 5%)
/ items = ("Herzlich Willkommen!")
/ position = (50, 40)
</text>


<text intronext>
/ fontstyle = ("Arial", 3%)
/ items = ("Drücken Sie eine beliebige Taste um zu beginnen.")
/ position = (50, 80)
</text>

<trial intro>
/ stimulustimes = [0=logo, introtext1, introtext2; 500=intronext]
/ validresponse = (anyresponse)
</trial>




<page start>
^^Herzlich Willkommen und Danke für Ihre Teilnahme!
^^Bevor Sie beginnen, lesen Sie bitte die folgenden Informationen zu dieser Studie.

^^In dieser Studie interessieren wir uns für Aufmerksamkeitsprozesse. Sie werden im Folgenden gebeten, einen Text zu lesen, verschiedene Fragebogen zu beantworten sowie eine Bildklassifikationsaufgabe zu bearbeiten.
Insgesamt wird die Teilnahme etwa 35 bis 45 Minuten dauern.

^^Die Teilnahme an dieser Studie ist freiwillig. Weiterhin werden alle in dieser Studie erhobenen Daten anonym gespeichert.
Es ist daher unmöglich Untersuchungsteilnehmer rückwirkend zu identifizieren.
Die Daten werden nicht individuell, sondern nur über alle TeilnehmerInnen hinweg ausgewertet. 

^^Sie haben das Recht, die Teilnahme jederzeit ohne Angabe von Gründen abzubrechen, ohne dass Ihnen dadurch Nachteile entstehen.
Der Anspruch auf Vergütung entfällt in diesem Fall jedoch.

^^Nach Abschluss der Studie werden wir Sie gerne über die wissenschaftliche Fragestellung und die Ziele der Untersuchung vollständig aufklären, sofern Sie dies wünschen.

^^^^Wenn Sie die oben stehenden Informationen über die Studie gelesen haben und bereit sind, daran teilzunehmen, klicken Sie bitte auf WEITER, um zu beginnen.
^^Falls Sie nicht teilnehmen möchten oder die Untersuchung abbrechen möchten, wenden Sie sich bitte an die Versuchsleitung.
</page>


<block intro>
/trials = [1=intro]
/ postinstructions = (start)
/ branch = [if (values.group == 1 ) block.david1]
/ branch = [if (values.group == 2 ) block.david2]
/ branch = [if (values.group == 3 ) block.david3]
/ branch = [if (values.group == 4 ) block.david4]
</block>




********************************
********** Target: David ***
********************************


<htmlpage david1>
/ file = "david_B_1.html"
</htmlpage>

<htmlpage david2>
/ file = "david_B_2.html"
</htmlpage>

<htmlpage david3>
/ file = "david_B_3.html"
</htmlpage>

<htmlpage david4>
/ file = "david_B_4.html"
</htmlpage>

<page david_intro>
^^Auf der nächsten Seite stellen wir Ihnen eine Person vor. Bitte lesen Sie sich den Text dazu aufmerksam durch.
Später werden wir Ihnen einige Fragen zu dieser Person stellen.
</page>

<block david1>
/ preinstructions = (david_intro)
/ postinstructions = (david1)
</block>

<block david2>
/ preinstructions = (david_intro)
/ postinstructions = (david2)
</block>

<block david3>
/ preinstructions = (david_intro)
/ postinstructions = (david3)
</block>

<block david4>
/ preinstructions = (david_intro)
/ postinstructions = (david4)
</block>


********************************************
*******Reversed Correlation**********
********************************************
<page rating_task_davids>
^^In der nun folgenden visuellen Aufgabe werden Ihnen jeweils zwei Gesichter präsentiert. Bitte wählen Sie jeweils das Gesicht aus, welches Ihrer Meinung nach eher David ähnelt.
^^Sollten Sie Zweifel an Ihrer Entscheidung haben, antworten Sie einfach aus dem Bauch heraus.
^^Um Ihre visuelle Leistung in diesem Test stabil schätzen zu können, werden Sie 400 dieser Entscheidungen treffen.
Wir möchten Sie bitten, konzentriert und aufmerksam zu bleiben und gleichzeitig zügig zu antworten.
^^Um Ihnen dies zu erleichtern, haben wir die große Menge an Durchgängen in vier gleich große Blöcke aufgeteilt. Zwischen den Blöcken können Sie immer eine kurze Pause machen.
^^^^Bitte drücken Sie die Taste "E" für das linke Gesicht und die Taste "I" für das rechte Gesicht! 
</page>

<block facial_davids>
/ preinstructions=(rating_task_davids)
/ trials = [1-100 = noreplace(binary_face_davids); 101=interim1; 102-201 = noreplace(binary_face_davids); 202=interim2;
 203-302= noreplace(binary_face_davids); 303=interim3; 304-403= noreplace(binary_face_davids); 404=interimend]
</block>




<text zwischenblock1a>
/ position = (50,45)
/ items = ("Sie haben nun den ersten von vier Blöcken geschafft!")
/ numitems = 1
</text>

<text zwischenblock1b>
/ position = (50,80)
/ items = ("Weiter geht es durch Drücken der Enter-Taste!")
/ numitems = 1
</text>

<text zwischenblock2>
/ position = (50,45)
/ items = ("Sie haben nun den zweiten von vier Blöcken geschafft!")
/ numitems = 1
</text>

<text zwischenblock3>
/ position = (50,45)
/ items = ("Sie haben nun den dritten von vier Blöcken geschafft!")
/ numitems = 1
</text>

<text zwischenblockend>
/ position = (50,45)
/size = (900,200)
/ items = ("Sie haben nun diesen Teil der Untersuchung geschafft! ~nWenn Sie bereit sind drücken Sie bitte die Enter-Taste um fortzufahren.")
/ numitems = 1
</text>

<shape erase>
/ position = (50,10)
/ size = (80%,10%)
/ color = white
</shape>



<trial interim1>
/ stimulustimes = [1=erase, zwischenblock1a,zwischenblock1b]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>

<trial interim2>
/ stimulustimes = [1=erase, zwischenblock2,zwischenblock1b]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>

<trial interim3>
/ stimulustimes = [1=erase, zwischenblock3, zwischenblock1b]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>

<trial interimend>
/ stimulustimes = [1=erase, zwischenblockend]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>



<text face_davids>
/ position = (50,10)
/ items = ("Welches Gesicht ähnelt David Ihrer Meinung nach eher?")
/ size = (80%,5%)
/ erase = false
</text>


<TRIAL binary_face_davids> 
/ stimulustimes= [1 = face_davids, stimuli0, stimuli1] 
/ validresponse = (18, 23)
</trial>


<picture stimuli0>
/ position = (25, 50)
/ numitems = 400
/ items = stimuli0
/ select = noreplace
</picture>

<picture stimuli1>
/ position = (75, 50)
/ numitems = 400
/ items = stimuli1
/ select = current(stimuli0)
</picture>

<item stimuli0>
/1= "stimuli/as2_MNES_1_1.jpg"
/2= "stimuli/as2_MNES_1_2.jpg"
/3= "stimuli/as2_MNES_1_3.jpg"
/4= "stimuli/as2_MNES_1_4.jpg"
/5= "stimuli/as2_MNES_1_5.jpg"
/6= "stimuli/as2_MNES_1_6.jpg"
/7= "stimuli/as2_MNES_1_7.jpg"
/8= "stimuli/as2_MNES_1_8.jpg"
/9= "stimuli/as2_MNES_1_9.jpg"
/10= "stimuli/as2_MNES_1_10.jpg"
/11= "stimuli/as2_MNES_1_11.jpg"
/12= "stimuli/as2_MNES_1_12.jpg"
/13= "stimuli/as2_MNES_1_13.jpg"
/14= "stimuli/as2_MNES_1_14.jpg"
/15= "stimuli/as2_MNES_1_15.jpg"
/16= "stimuli/as2_MNES_1_16.jpg"
/17= "stimuli/as2_MNES_1_17.jpg"
/18= "stimuli/as2_MNES_1_18.jpg"
/19= "stimuli/as2_MNES_1_19.jpg"
/20= "stimuli/as2_MNES_1_20.jpg"
/21= "stimuli/as2_MNES_1_21.jpg"
/22= "stimuli/as2_MNES_1_22.jpg"
/23= "stimuli/as2_MNES_1_23.jpg"
/24= "stimuli/as2_MNES_1_24.jpg"
/25= "stimuli/as2_MNES_1_25.jpg"
/26= "stimuli/as2_MNES_1_26.jpg"
/27= "stimuli/as2_MNES_1_27.jpg"
/28= "stimuli/as2_MNES_1_28.jpg"
/29= "stimuli/as2_MNES_1_29.jpg"
/30= "stimuli/as2_MNES_1_30.jpg"
/31= "stimuli/as2_MNES_1_31.jpg"
/32= "stimuli/as2_MNES_1_32.jpg"
/33= "stimuli/as2_MNES_1_33.jpg"
/34= "stimuli/as2_MNES_1_34.jpg"
/35= "stimuli/as2_MNES_1_35.jpg"
/36= "stimuli/as2_MNES_1_36.jpg"
/37= "stimuli/as2_MNES_1_37.jpg"
/38= "stimuli/as2_MNES_1_38.jpg"
/39= "stimuli/as2_MNES_1_39.jpg"
/40= "stimuli/as2_MNES_1_40.jpg"
/41= "stimuli/as2_MNES_1_41.jpg"
/42= "stimuli/as2_MNES_1_42.jpg"
/43= "stimuli/as2_MNES_1_43.jpg"
/44= "stimuli/as2_MNES_1_44.jpg"
/45= "stimuli/as2_MNES_1_45.jpg"
/46= "stimuli/as2_MNES_1_46.jpg"
/47= "stimuli/as2_MNES_1_47.jpg"
/48= "stimuli/as2_MNES_1_48.jpg"
/49= "stimuli/as2_MNES_1_49.jpg"
/50= "stimuli/as2_MNES_1_50.jpg"
/51= "stimuli/as2_MNES_1_51.jpg"
/52= "stimuli/as2_MNES_1_52.jpg"
/53= "stimuli/as2_MNES_1_53.jpg"
/54= "stimuli/as2_MNES_1_54.jpg"
/55= "stimuli/as2_MNES_1_55.jpg"
/56= "stimuli/as2_MNES_1_56.jpg"
/57= "stimuli/as2_MNES_1_57.jpg"
/58= "stimuli/as2_MNES_1_58.jpg"
/59= "stimuli/as2_MNES_1_59.jpg"
/60= "stimuli/as2_MNES_1_60.jpg"
/61= "stimuli/as2_MNES_1_61.jpg"
/62= "stimuli/as2_MNES_1_62.jpg"
/63= "stimuli/as2_MNES_1_63.jpg"
/64= "stimuli/as2_MNES_1_64.jpg"
/65= "stimuli/as2_MNES_1_65.jpg"
/66= "stimuli/as2_MNES_1_66.jpg"
/67= "stimuli/as2_MNES_1_67.jpg"
/68= "stimuli/as2_MNES_1_68.jpg"
/69= "stimuli/as2_MNES_1_69.jpg"
/70= "stimuli/as2_MNES_1_70.jpg"
/71= "stimuli/as2_MNES_1_71.jpg"
/72= "stimuli/as2_MNES_1_72.jpg"
/73= "stimuli/as2_MNES_1_73.jpg"
/74= "stimuli/as2_MNES_1_74.jpg"
/75= "stimuli/as2_MNES_1_75.jpg"
/76= "stimuli/as2_MNES_1_76.jpg"
/77= "stimuli/as2_MNES_1_77.jpg"
/78= "stimuli/as2_MNES_1_78.jpg"
/79= "stimuli/as2_MNES_1_79.jpg"
/80= "stimuli/as2_MNES_1_80.jpg"
/81= "stimuli/as2_MNES_1_81.jpg"
/82= "stimuli/as2_MNES_1_82.jpg"
/83= "stimuli/as2_MNES_1_83.jpg"
/84= "stimuli/as2_MNES_1_84.jpg"
/85= "stimuli/as2_MNES_1_85.jpg"
/86= "stimuli/as2_MNES_1_86.jpg"
/87= "stimuli/as2_MNES_1_87.jpg"
/88= "stimuli/as2_MNES_1_88.jpg"
/89= "stimuli/as2_MNES_1_89.jpg"
/90= "stimuli/as2_MNES_1_90.jpg"
/91= "stimuli/as2_MNES_1_91.jpg"
/92= "stimuli/as2_MNES_1_92.jpg"
/93= "stimuli/as2_MNES_1_93.jpg"
/94= "stimuli/as2_MNES_1_94.jpg"
/95= "stimuli/as2_MNES_1_95.jpg"
/96= "stimuli/as2_MNES_1_96.jpg"
/97= "stimuli/as2_MNES_1_97.jpg"
/98= "stimuli/as2_MNES_1_98.jpg"
/99= "stimuli/as2_MNES_1_99.jpg"
/100= "stimuli/as2_MNES_1_100.jpg"
/101= "stimuli/as2_MNES_1_101.jpg"
/102= "stimuli/as2_MNES_1_102.jpg"
/103= "stimuli/as2_MNES_1_103.jpg"
/104= "stimuli/as2_MNES_1_104.jpg"
/105= "stimuli/as2_MNES_1_105.jpg"
/106= "stimuli/as2_MNES_1_106.jpg"
/107= "stimuli/as2_MNES_1_107.jpg"
/108= "stimuli/as2_MNES_1_108.jpg"
/109= "stimuli/as2_MNES_1_109.jpg"
/110= "stimuli/as2_MNES_1_110.jpg"
/111= "stimuli/as2_MNES_1_111.jpg"
/112= "stimuli/as2_MNES_1_112.jpg"
/113= "stimuli/as2_MNES_1_113.jpg"
/114= "stimuli/as2_MNES_1_114.jpg"
/115= "stimuli/as2_MNES_1_115.jpg"
/116= "stimuli/as2_MNES_1_116.jpg"
/117= "stimuli/as2_MNES_1_117.jpg"
/118= "stimuli/as2_MNES_1_118.jpg"
/119= "stimuli/as2_MNES_1_119.jpg"
/120= "stimuli/as2_MNES_1_120.jpg"
/121= "stimuli/as2_MNES_1_121.jpg"
/122= "stimuli/as2_MNES_1_122.jpg"
/123= "stimuli/as2_MNES_1_123.jpg"
/124= "stimuli/as2_MNES_1_124.jpg"
/125= "stimuli/as2_MNES_1_125.jpg"
/126= "stimuli/as2_MNES_1_126.jpg"
/127= "stimuli/as2_MNES_1_127.jpg"
/128= "stimuli/as2_MNES_1_128.jpg"
/129= "stimuli/as2_MNES_1_129.jpg"
/130= "stimuli/as2_MNES_1_130.jpg"
/131= "stimuli/as2_MNES_1_131.jpg"
/132= "stimuli/as2_MNES_1_132.jpg"
/133= "stimuli/as2_MNES_1_133.jpg"
/134= "stimuli/as2_MNES_1_134.jpg"
/135= "stimuli/as2_MNES_1_135.jpg"
/136= "stimuli/as2_MNES_1_136.jpg"
/137= "stimuli/as2_MNES_1_137.jpg"
/138= "stimuli/as2_MNES_1_138.jpg"
/139= "stimuli/as2_MNES_1_139.jpg"
/140= "stimuli/as2_MNES_1_140.jpg"
/141= "stimuli/as2_MNES_1_141.jpg"
/142= "stimuli/as2_MNES_1_142.jpg"
/143= "stimuli/as2_MNES_1_143.jpg"
/144= "stimuli/as2_MNES_1_144.jpg"
/145= "stimuli/as2_MNES_1_145.jpg"
/146= "stimuli/as2_MNES_1_146.jpg"
/147= "stimuli/as2_MNES_1_147.jpg"
/148= "stimuli/as2_MNES_1_148.jpg"
/149= "stimuli/as2_MNES_1_149.jpg"
/150= "stimuli/as2_MNES_1_150.jpg"
/151= "stimuli/as2_MNES_1_151.jpg"
/152= "stimuli/as2_MNES_1_152.jpg"
/153= "stimuli/as2_MNES_1_153.jpg"
/154= "stimuli/as2_MNES_1_154.jpg"
/155= "stimuli/as2_MNES_1_155.jpg"
/156= "stimuli/as2_MNES_1_156.jpg"
/157= "stimuli/as2_MNES_1_157.jpg"
/158= "stimuli/as2_MNES_1_158.jpg"
/159= "stimuli/as2_MNES_1_159.jpg"
/160= "stimuli/as2_MNES_1_160.jpg"
/161= "stimuli/as2_MNES_1_161.jpg"
/162= "stimuli/as2_MNES_1_162.jpg"
/163= "stimuli/as2_MNES_1_163.jpg"
/164= "stimuli/as2_MNES_1_164.jpg"
/165= "stimuli/as2_MNES_1_165.jpg"
/166= "stimuli/as2_MNES_1_166.jpg"
/167= "stimuli/as2_MNES_1_167.jpg"
/168= "stimuli/as2_MNES_1_168.jpg"
/169= "stimuli/as2_MNES_1_169.jpg"
/170= "stimuli/as2_MNES_1_170.jpg"
/171= "stimuli/as2_MNES_1_171.jpg"
/172= "stimuli/as2_MNES_1_172.jpg"
/173= "stimuli/as2_MNES_1_173.jpg"
/174= "stimuli/as2_MNES_1_174.jpg"
/175= "stimuli/as2_MNES_1_175.jpg"
/176= "stimuli/as2_MNES_1_176.jpg"
/177= "stimuli/as2_MNES_1_177.jpg"
/178= "stimuli/as2_MNES_1_178.jpg"
/179= "stimuli/as2_MNES_1_179.jpg"
/180= "stimuli/as2_MNES_1_180.jpg"
/181= "stimuli/as2_MNES_1_181.jpg"
/182= "stimuli/as2_MNES_1_182.jpg"
/183= "stimuli/as2_MNES_1_183.jpg"
/184= "stimuli/as2_MNES_1_184.jpg"
/185= "stimuli/as2_MNES_1_185.jpg"
/186= "stimuli/as2_MNES_1_186.jpg"
/187= "stimuli/as2_MNES_1_187.jpg"
/188= "stimuli/as2_MNES_1_188.jpg"
/189= "stimuli/as2_MNES_1_189.jpg"
/190= "stimuli/as2_MNES_1_190.jpg"
/191= "stimuli/as2_MNES_1_191.jpg"
/192= "stimuli/as2_MNES_1_192.jpg"
/193= "stimuli/as2_MNES_1_193.jpg"
/194= "stimuli/as2_MNES_1_194.jpg"
/195= "stimuli/as2_MNES_1_195.jpg"
/196= "stimuli/as2_MNES_1_196.jpg"
/197= "stimuli/as2_MNES_1_197.jpg"
/198= "stimuli/as2_MNES_1_198.jpg"
/199= "stimuli/as2_MNES_1_199.jpg"
/200= "stimuli/as2_MNES_1_200.jpg"
/201= "stimuli/as2_MNES_1_201.jpg"
/202= "stimuli/as2_MNES_1_202.jpg"
/203= "stimuli/as2_MNES_1_203.jpg"
/204= "stimuli/as2_MNES_1_204.jpg"
/205= "stimuli/as2_MNES_1_205.jpg"
/206= "stimuli/as2_MNES_1_206.jpg"
/207= "stimuli/as2_MNES_1_207.jpg"
/208= "stimuli/as2_MNES_1_208.jpg"
/209= "stimuli/as2_MNES_1_209.jpg"
/210= "stimuli/as2_MNES_1_210.jpg"
/211= "stimuli/as2_MNES_1_211.jpg"
/212= "stimuli/as2_MNES_1_212.jpg"
/213= "stimuli/as2_MNES_1_213.jpg"
/214= "stimuli/as2_MNES_1_214.jpg"
/215= "stimuli/as2_MNES_1_215.jpg"
/216= "stimuli/as2_MNES_1_216.jpg"
/217= "stimuli/as2_MNES_1_217.jpg"
/218= "stimuli/as2_MNES_1_218.jpg"
/219= "stimuli/as2_MNES_1_219.jpg"
/220= "stimuli/as2_MNES_1_220.jpg"
/221= "stimuli/as2_MNES_1_221.jpg"
/222= "stimuli/as2_MNES_1_222.jpg"
/223= "stimuli/as2_MNES_1_223.jpg"
/224= "stimuli/as2_MNES_1_224.jpg"
/225= "stimuli/as2_MNES_1_225.jpg"
/226= "stimuli/as2_MNES_1_226.jpg"
/227= "stimuli/as2_MNES_1_227.jpg"
/228= "stimuli/as2_MNES_1_228.jpg"
/229= "stimuli/as2_MNES_1_229.jpg"
/230= "stimuli/as2_MNES_1_230.jpg"
/231= "stimuli/as2_MNES_1_231.jpg"
/232= "stimuli/as2_MNES_1_232.jpg"
/233= "stimuli/as2_MNES_1_233.jpg"
/234= "stimuli/as2_MNES_1_234.jpg"
/235= "stimuli/as2_MNES_1_235.jpg"
/236= "stimuli/as2_MNES_1_236.jpg"
/237= "stimuli/as2_MNES_1_237.jpg"
/238= "stimuli/as2_MNES_1_238.jpg"
/239= "stimuli/as2_MNES_1_239.jpg"
/240= "stimuli/as2_MNES_1_240.jpg"
/241= "stimuli/as2_MNES_1_241.jpg"
/242= "stimuli/as2_MNES_1_242.jpg"
/243= "stimuli/as2_MNES_1_243.jpg"
/244= "stimuli/as2_MNES_1_244.jpg"
/245= "stimuli/as2_MNES_1_245.jpg"
/246= "stimuli/as2_MNES_1_246.jpg"
/247= "stimuli/as2_MNES_1_247.jpg"
/248= "stimuli/as2_MNES_1_248.jpg"
/249= "stimuli/as2_MNES_1_249.jpg"
/250= "stimuli/as2_MNES_1_250.jpg"
/251= "stimuli/as2_MNES_1_251.jpg"
/252= "stimuli/as2_MNES_1_252.jpg"
/253= "stimuli/as2_MNES_1_253.jpg"
/254= "stimuli/as2_MNES_1_254.jpg"
/255= "stimuli/as2_MNES_1_255.jpg"
/256= "stimuli/as2_MNES_1_256.jpg"
/257= "stimuli/as2_MNES_1_257.jpg"
/258= "stimuli/as2_MNES_1_258.jpg"
/259= "stimuli/as2_MNES_1_259.jpg"
/260= "stimuli/as2_MNES_1_260.jpg"
/261= "stimuli/as2_MNES_1_261.jpg"
/262= "stimuli/as2_MNES_1_262.jpg"
/263= "stimuli/as2_MNES_1_263.jpg"
/264= "stimuli/as2_MNES_1_264.jpg"
/265= "stimuli/as2_MNES_1_265.jpg"
/266= "stimuli/as2_MNES_1_266.jpg"
/267= "stimuli/as2_MNES_1_267.jpg"
/268= "stimuli/as2_MNES_1_268.jpg"
/269= "stimuli/as2_MNES_1_269.jpg"
/270= "stimuli/as2_MNES_1_270.jpg"
/271= "stimuli/as2_MNES_1_271.jpg"
/272= "stimuli/as2_MNES_1_272.jpg"
/273= "stimuli/as2_MNES_1_273.jpg"
/274= "stimuli/as2_MNES_1_274.jpg"
/275= "stimuli/as2_MNES_1_275.jpg"
/276= "stimuli/as2_MNES_1_276.jpg"
/277= "stimuli/as2_MNES_1_277.jpg"
/278= "stimuli/as2_MNES_1_278.jpg"
/279= "stimuli/as2_MNES_1_279.jpg"
/280= "stimuli/as2_MNES_1_280.jpg"
/281= "stimuli/as2_MNES_1_281.jpg"
/282= "stimuli/as2_MNES_1_282.jpg"
/283= "stimuli/as2_MNES_1_283.jpg"
/284= "stimuli/as2_MNES_1_284.jpg"
/285= "stimuli/as2_MNES_1_285.jpg"
/286= "stimuli/as2_MNES_1_286.jpg"
/287= "stimuli/as2_MNES_1_287.jpg"
/288= "stimuli/as2_MNES_1_288.jpg"
/289= "stimuli/as2_MNES_1_289.jpg"
/290= "stimuli/as2_MNES_1_290.jpg"
/291= "stimuli/as2_MNES_1_291.jpg"
/292= "stimuli/as2_MNES_1_292.jpg"
/293= "stimuli/as2_MNES_1_293.jpg"
/294= "stimuli/as2_MNES_1_294.jpg"
/295= "stimuli/as2_MNES_1_295.jpg"
/296= "stimuli/as2_MNES_1_296.jpg"
/297= "stimuli/as2_MNES_1_297.jpg"
/298= "stimuli/as2_MNES_1_298.jpg"
/299= "stimuli/as2_MNES_1_299.jpg"
/300= "stimuli/as2_MNES_1_300.jpg"
/301= "stimuli/as2_MNES_1_301.jpg"
/302= "stimuli/as2_MNES_1_302.jpg"
/303= "stimuli/as2_MNES_1_303.jpg"
/304= "stimuli/as2_MNES_1_304.jpg"
/305= "stimuli/as2_MNES_1_305.jpg"
/306= "stimuli/as2_MNES_1_306.jpg"
/307= "stimuli/as2_MNES_1_307.jpg"
/308= "stimuli/as2_MNES_1_308.jpg"
/309= "stimuli/as2_MNES_1_309.jpg"
/310= "stimuli/as2_MNES_1_310.jpg"
/311= "stimuli/as2_MNES_1_311.jpg"
/312= "stimuli/as2_MNES_1_312.jpg"
/313= "stimuli/as2_MNES_1_313.jpg"
/314= "stimuli/as2_MNES_1_314.jpg"
/315= "stimuli/as2_MNES_1_315.jpg"
/316= "stimuli/as2_MNES_1_316.jpg"
/317= "stimuli/as2_MNES_1_317.jpg"
/318= "stimuli/as2_MNES_1_318.jpg"
/319= "stimuli/as2_MNES_1_319.jpg"
/320= "stimuli/as2_MNES_1_320.jpg"
/321= "stimuli/as2_MNES_1_321.jpg"
/322= "stimuli/as2_MNES_1_322.jpg"
/323= "stimuli/as2_MNES_1_323.jpg"
/324= "stimuli/as2_MNES_1_324.jpg"
/325= "stimuli/as2_MNES_1_325.jpg"
/326= "stimuli/as2_MNES_1_326.jpg"
/327= "stimuli/as2_MNES_1_327.jpg"
/328= "stimuli/as2_MNES_1_328.jpg"
/329= "stimuli/as2_MNES_1_329.jpg"
/330= "stimuli/as2_MNES_1_330.jpg"
/331= "stimuli/as2_MNES_1_331.jpg"
/332= "stimuli/as2_MNES_1_332.jpg"
/333= "stimuli/as2_MNES_1_333.jpg"
/334= "stimuli/as2_MNES_1_334.jpg"
/335= "stimuli/as2_MNES_1_335.jpg"
/336= "stimuli/as2_MNES_1_336.jpg"
/337= "stimuli/as2_MNES_1_337.jpg"
/338= "stimuli/as2_MNES_1_338.jpg"
/339= "stimuli/as2_MNES_1_339.jpg"
/340= "stimuli/as2_MNES_1_340.jpg"
/341= "stimuli/as2_MNES_1_341.jpg"
/342= "stimuli/as2_MNES_1_342.jpg"
/343= "stimuli/as2_MNES_1_343.jpg"
/344= "stimuli/as2_MNES_1_344.jpg"
/345= "stimuli/as2_MNES_1_345.jpg"
/346= "stimuli/as2_MNES_1_346.jpg"
/347= "stimuli/as2_MNES_1_347.jpg"
/348= "stimuli/as2_MNES_1_348.jpg"
/349= "stimuli/as2_MNES_1_349.jpg"
/350= "stimuli/as2_MNES_1_350.jpg"
/351= "stimuli/as2_MNES_1_351.jpg"
/352= "stimuli/as2_MNES_1_352.jpg"
/353= "stimuli/as2_MNES_1_353.jpg"
/354= "stimuli/as2_MNES_1_354.jpg"
/355= "stimuli/as2_MNES_1_355.jpg"
/356= "stimuli/as2_MNES_1_356.jpg"
/357= "stimuli/as2_MNES_1_357.jpg"
/358= "stimuli/as2_MNES_1_358.jpg"
/359= "stimuli/as2_MNES_1_359.jpg"
/360= "stimuli/as2_MNES_1_360.jpg"
/361= "stimuli/as2_MNES_1_361.jpg"
/362= "stimuli/as2_MNES_1_362.jpg"
/363= "stimuli/as2_MNES_1_363.jpg"
/364= "stimuli/as2_MNES_1_364.jpg"
/365= "stimuli/as2_MNES_1_365.jpg"
/366= "stimuli/as2_MNES_1_366.jpg"
/367= "stimuli/as2_MNES_1_367.jpg"
/368= "stimuli/as2_MNES_1_368.jpg"
/369= "stimuli/as2_MNES_1_369.jpg"
/370= "stimuli/as2_MNES_1_370.jpg"
/371= "stimuli/as2_MNES_1_371.jpg"
/372= "stimuli/as2_MNES_1_372.jpg"
/373= "stimuli/as2_MNES_1_373.jpg"
/374= "stimuli/as2_MNES_1_374.jpg"
/375= "stimuli/as2_MNES_1_375.jpg"
/376= "stimuli/as2_MNES_1_376.jpg"
/377= "stimuli/as2_MNES_1_377.jpg"
/378= "stimuli/as2_MNES_1_378.jpg"
/379= "stimuli/as2_MNES_1_379.jpg"
/380= "stimuli/as2_MNES_1_380.jpg"
/381= "stimuli/as2_MNES_1_381.jpg"
/382= "stimuli/as2_MNES_1_382.jpg"
/383= "stimuli/as2_MNES_1_383.jpg"
/384= "stimuli/as2_MNES_1_384.jpg"
/385= "stimuli/as2_MNES_1_385.jpg"
/386= "stimuli/as2_MNES_1_386.jpg"
/387= "stimuli/as2_MNES_1_387.jpg"
/388= "stimuli/as2_MNES_1_388.jpg"
/389= "stimuli/as2_MNES_1_389.jpg"
/390= "stimuli/as2_MNES_1_390.jpg"
/391= "stimuli/as2_MNES_1_391.jpg"
/392= "stimuli/as2_MNES_1_392.jpg"
/393= "stimuli/as2_MNES_1_393.jpg"
/394= "stimuli/as2_MNES_1_394.jpg"
/395= "stimuli/as2_MNES_1_395.jpg"
/396= "stimuli/as2_MNES_1_396.jpg"
/397= "stimuli/as2_MNES_1_397.jpg"
/398= "stimuli/as2_MNES_1_398.jpg"
/399= "stimuli/as2_MNES_1_399.jpg"
/400= "stimuli/as2_MNES_1_0.jpg"
</item>

<item stimuli1>
/1= "stimuli/as2_MNES_1_1_neg.jpg"
/2= "stimuli/as2_MNES_1_2_neg.jpg"
/3= "stimuli/as2_MNES_1_3_neg.jpg"
/4= "stimuli/as2_MNES_1_4_neg.jpg"
/5= "stimuli/as2_MNES_1_5_neg.jpg"
/6= "stimuli/as2_MNES_1_6_neg.jpg"
/7= "stimuli/as2_MNES_1_7_neg.jpg"
/8= "stimuli/as2_MNES_1_8_neg.jpg"
/9= "stimuli/as2_MNES_1_9_neg.jpg"
/10= "stimuli/as2_MNES_1_10_neg.jpg"
/11= "stimuli/as2_MNES_1_11_neg.jpg"
/12= "stimuli/as2_MNES_1_12_neg.jpg"
/13= "stimuli/as2_MNES_1_13_neg.jpg"
/14= "stimuli/as2_MNES_1_14_neg.jpg"
/15= "stimuli/as2_MNES_1_15_neg.jpg"
/16= "stimuli/as2_MNES_1_16_neg.jpg"
/17= "stimuli/as2_MNES_1_17_neg.jpg"
/18= "stimuli/as2_MNES_1_18_neg.jpg"
/19= "stimuli/as2_MNES_1_19_neg.jpg"
/20= "stimuli/as2_MNES_1_20_neg.jpg"
/21= "stimuli/as2_MNES_1_21_neg.jpg"
/22= "stimuli/as2_MNES_1_22_neg.jpg"
/23= "stimuli/as2_MNES_1_23_neg.jpg"
/24= "stimuli/as2_MNES_1_24_neg.jpg"
/25= "stimuli/as2_MNES_1_25_neg.jpg"
/26= "stimuli/as2_MNES_1_26_neg.jpg"
/27= "stimuli/as2_MNES_1_27_neg.jpg"
/28= "stimuli/as2_MNES_1_28_neg.jpg"
/29= "stimuli/as2_MNES_1_29_neg.jpg"
/30= "stimuli/as2_MNES_1_30_neg.jpg"
/31= "stimuli/as2_MNES_1_31_neg.jpg"
/32= "stimuli/as2_MNES_1_32_neg.jpg"
/33= "stimuli/as2_MNES_1_33_neg.jpg"
/34= "stimuli/as2_MNES_1_34_neg.jpg"
/35= "stimuli/as2_MNES_1_35_neg.jpg"
/36= "stimuli/as2_MNES_1_36_neg.jpg"
/37= "stimuli/as2_MNES_1_37_neg.jpg"
/38= "stimuli/as2_MNES_1_38_neg.jpg"
/39= "stimuli/as2_MNES_1_39_neg.jpg"
/40= "stimuli/as2_MNES_1_40_neg.jpg"
/41= "stimuli/as2_MNES_1_41_neg.jpg"
/42= "stimuli/as2_MNES_1_42_neg.jpg"
/43= "stimuli/as2_MNES_1_43_neg.jpg"
/44= "stimuli/as2_MNES_1_44_neg.jpg"
/45= "stimuli/as2_MNES_1_45_neg.jpg"
/46= "stimuli/as2_MNES_1_46_neg.jpg"
/47= "stimuli/as2_MNES_1_47_neg.jpg"
/48= "stimuli/as2_MNES_1_48_neg.jpg"
/49= "stimuli/as2_MNES_1_49_neg.jpg"
/50= "stimuli/as2_MNES_1_50_neg.jpg"
/51= "stimuli/as2_MNES_1_51_neg.jpg"
/52= "stimuli/as2_MNES_1_52_neg.jpg"
/53= "stimuli/as2_MNES_1_53_neg.jpg"
/54= "stimuli/as2_MNES_1_54_neg.jpg"
/55= "stimuli/as2_MNES_1_55_neg.jpg"
/56= "stimuli/as2_MNES_1_56_neg.jpg"
/57= "stimuli/as2_MNES_1_57_neg.jpg"
/58= "stimuli/as2_MNES_1_58_neg.jpg"
/59= "stimuli/as2_MNES_1_59_neg.jpg"
/60= "stimuli/as2_MNES_1_60_neg.jpg"
/61= "stimuli/as2_MNES_1_61_neg.jpg"
/62= "stimuli/as2_MNES_1_62_neg.jpg"
/63= "stimuli/as2_MNES_1_63_neg.jpg"
/64= "stimuli/as2_MNES_1_64_neg.jpg"
/65= "stimuli/as2_MNES_1_65_neg.jpg"
/66= "stimuli/as2_MNES_1_66_neg.jpg"
/67= "stimuli/as2_MNES_1_67_neg.jpg"
/68= "stimuli/as2_MNES_1_68_neg.jpg"
/69= "stimuli/as2_MNES_1_69_neg.jpg"
/70= "stimuli/as2_MNES_1_70_neg.jpg"
/71= "stimuli/as2_MNES_1_71_neg.jpg"
/72= "stimuli/as2_MNES_1_72_neg.jpg"
/73= "stimuli/as2_MNES_1_73_neg.jpg"
/74= "stimuli/as2_MNES_1_74_neg.jpg"
/75= "stimuli/as2_MNES_1_75_neg.jpg"
/76= "stimuli/as2_MNES_1_76_neg.jpg"
/77= "stimuli/as2_MNES_1_77_neg.jpg"
/78= "stimuli/as2_MNES_1_78_neg.jpg"
/79= "stimuli/as2_MNES_1_79_neg.jpg"
/80= "stimuli/as2_MNES_1_80_neg.jpg"
/81= "stimuli/as2_MNES_1_81_neg.jpg"
/82= "stimuli/as2_MNES_1_82_neg.jpg"
/83= "stimuli/as2_MNES_1_83_neg.jpg"
/84= "stimuli/as2_MNES_1_84_neg.jpg"
/85= "stimuli/as2_MNES_1_85_neg.jpg"
/86= "stimuli/as2_MNES_1_86_neg.jpg"
/87= "stimuli/as2_MNES_1_87_neg.jpg"
/88= "stimuli/as2_MNES_1_88_neg.jpg"
/89= "stimuli/as2_MNES_1_89_neg.jpg"
/90= "stimuli/as2_MNES_1_90_neg.jpg"
/91= "stimuli/as2_MNES_1_91_neg.jpg"
/92= "stimuli/as2_MNES_1_92_neg.jpg"
/93= "stimuli/as2_MNES_1_93_neg.jpg"
/94= "stimuli/as2_MNES_1_94_neg.jpg"
/95= "stimuli/as2_MNES_1_95_neg.jpg"
/96= "stimuli/as2_MNES_1_96_neg.jpg"
/97= "stimuli/as2_MNES_1_97_neg.jpg"
/98= "stimuli/as2_MNES_1_98_neg.jpg"
/99= "stimuli/as2_MNES_1_99_neg.jpg"
/100= "stimuli/as2_MNES_1_100_neg.jpg"
/101= "stimuli/as2_MNES_1_101_neg.jpg"
/102= "stimuli/as2_MNES_1_102_neg.jpg"
/103= "stimuli/as2_MNES_1_103_neg.jpg"
/104= "stimuli/as2_MNES_1_104_neg.jpg"
/105= "stimuli/as2_MNES_1_105_neg.jpg"
/106= "stimuli/as2_MNES_1_106_neg.jpg"
/107= "stimuli/as2_MNES_1_107_neg.jpg"
/108= "stimuli/as2_MNES_1_108_neg.jpg"
/109= "stimuli/as2_MNES_1_109_neg.jpg"
/110= "stimuli/as2_MNES_1_110_neg.jpg"
/111= "stimuli/as2_MNES_1_111_neg.jpg"
/112= "stimuli/as2_MNES_1_112_neg.jpg"
/113= "stimuli/as2_MNES_1_113_neg.jpg"
/114= "stimuli/as2_MNES_1_114_neg.jpg"
/115= "stimuli/as2_MNES_1_115_neg.jpg"
/116= "stimuli/as2_MNES_1_116_neg.jpg"
/117= "stimuli/as2_MNES_1_117_neg.jpg"
/118= "stimuli/as2_MNES_1_118_neg.jpg"
/119= "stimuli/as2_MNES_1_119_neg.jpg"
/120= "stimuli/as2_MNES_1_120_neg.jpg"
/121= "stimuli/as2_MNES_1_121_neg.jpg"
/122= "stimuli/as2_MNES_1_122_neg.jpg"
/123= "stimuli/as2_MNES_1_123_neg.jpg"
/124= "stimuli/as2_MNES_1_124_neg.jpg"
/125= "stimuli/as2_MNES_1_125_neg.jpg"
/126= "stimuli/as2_MNES_1_126_neg.jpg"
/127= "stimuli/as2_MNES_1_127_neg.jpg"
/128= "stimuli/as2_MNES_1_128_neg.jpg"
/129= "stimuli/as2_MNES_1_129_neg.jpg"
/130= "stimuli/as2_MNES_1_130_neg.jpg"
/131= "stimuli/as2_MNES_1_131_neg.jpg"
/132= "stimuli/as2_MNES_1_132_neg.jpg"
/133= "stimuli/as2_MNES_1_133_neg.jpg"
/134= "stimuli/as2_MNES_1_134_neg.jpg"
/135= "stimuli/as2_MNES_1_135_neg.jpg"
/136= "stimuli/as2_MNES_1_136_neg.jpg"
/137= "stimuli/as2_MNES_1_137_neg.jpg"
/138= "stimuli/as2_MNES_1_138_neg.jpg"
/139= "stimuli/as2_MNES_1_139_neg.jpg"
/140= "stimuli/as2_MNES_1_140_neg.jpg"
/141= "stimuli/as2_MNES_1_141_neg.jpg"
/142= "stimuli/as2_MNES_1_142_neg.jpg"
/143= "stimuli/as2_MNES_1_143_neg.jpg"
/144= "stimuli/as2_MNES_1_144_neg.jpg"
/145= "stimuli/as2_MNES_1_145_neg.jpg"
/146= "stimuli/as2_MNES_1_146_neg.jpg"
/147= "stimuli/as2_MNES_1_147_neg.jpg"
/148= "stimuli/as2_MNES_1_148_neg.jpg"
/149= "stimuli/as2_MNES_1_149_neg.jpg"
/150= "stimuli/as2_MNES_1_150_neg.jpg"
/151= "stimuli/as2_MNES_1_151_neg.jpg"
/152= "stimuli/as2_MNES_1_152_neg.jpg"
/153= "stimuli/as2_MNES_1_153_neg.jpg"
/154= "stimuli/as2_MNES_1_154_neg.jpg"
/155= "stimuli/as2_MNES_1_155_neg.jpg"
/156= "stimuli/as2_MNES_1_156_neg.jpg"
/157= "stimuli/as2_MNES_1_157_neg.jpg"
/158= "stimuli/as2_MNES_1_158_neg.jpg"
/159= "stimuli/as2_MNES_1_159_neg.jpg"
/160= "stimuli/as2_MNES_1_160_neg.jpg"
/161= "stimuli/as2_MNES_1_161_neg.jpg"
/162= "stimuli/as2_MNES_1_162_neg.jpg"
/163= "stimuli/as2_MNES_1_163_neg.jpg"
/164= "stimuli/as2_MNES_1_164_neg.jpg"
/165= "stimuli/as2_MNES_1_165_neg.jpg"
/166= "stimuli/as2_MNES_1_166_neg.jpg"
/167= "stimuli/as2_MNES_1_167_neg.jpg"
/168= "stimuli/as2_MNES_1_168_neg.jpg"
/169= "stimuli/as2_MNES_1_169_neg.jpg"
/170= "stimuli/as2_MNES_1_170_neg.jpg"
/171= "stimuli/as2_MNES_1_171_neg.jpg"
/172= "stimuli/as2_MNES_1_172_neg.jpg"
/173= "stimuli/as2_MNES_1_173_neg.jpg"
/174= "stimuli/as2_MNES_1_174_neg.jpg"
/175= "stimuli/as2_MNES_1_175_neg.jpg"
/176= "stimuli/as2_MNES_1_176_neg.jpg"
/177= "stimuli/as2_MNES_1_177_neg.jpg"
/178= "stimuli/as2_MNES_1_178_neg.jpg"
/179= "stimuli/as2_MNES_1_179_neg.jpg"
/180= "stimuli/as2_MNES_1_180_neg.jpg"
/181= "stimuli/as2_MNES_1_181_neg.jpg"
/182= "stimuli/as2_MNES_1_182_neg.jpg"
/183= "stimuli/as2_MNES_1_183_neg.jpg"
/184= "stimuli/as2_MNES_1_184_neg.jpg"
/185= "stimuli/as2_MNES_1_185_neg.jpg"
/186= "stimuli/as2_MNES_1_186_neg.jpg"
/187= "stimuli/as2_MNES_1_187_neg.jpg"
/188= "stimuli/as2_MNES_1_188_neg.jpg"
/189= "stimuli/as2_MNES_1_189_neg.jpg"
/190= "stimuli/as2_MNES_1_190_neg.jpg"
/191= "stimuli/as2_MNES_1_191_neg.jpg"
/192= "stimuli/as2_MNES_1_192_neg.jpg"
/193= "stimuli/as2_MNES_1_193_neg.jpg"
/194= "stimuli/as2_MNES_1_194_neg.jpg"
/195= "stimuli/as2_MNES_1_195_neg.jpg"
/196= "stimuli/as2_MNES_1_196_neg.jpg"
/197= "stimuli/as2_MNES_1_197_neg.jpg"
/198= "stimuli/as2_MNES_1_198_neg.jpg"
/199= "stimuli/as2_MNES_1_199_neg.jpg"
/200= "stimuli/as2_MNES_1_200_neg.jpg"
/201= "stimuli/as2_MNES_1_201_neg.jpg"
/202= "stimuli/as2_MNES_1_202_neg.jpg"
/203= "stimuli/as2_MNES_1_203_neg.jpg"
/204= "stimuli/as2_MNES_1_204_neg.jpg"
/205= "stimuli/as2_MNES_1_205_neg.jpg"
/206= "stimuli/as2_MNES_1_206_neg.jpg"
/207= "stimuli/as2_MNES_1_207_neg.jpg"
/208= "stimuli/as2_MNES_1_208_neg.jpg"
/209= "stimuli/as2_MNES_1_209_neg.jpg"
/210= "stimuli/as2_MNES_1_210_neg.jpg"
/211= "stimuli/as2_MNES_1_211_neg.jpg"
/212= "stimuli/as2_MNES_1_212_neg.jpg"
/213= "stimuli/as2_MNES_1_213_neg.jpg"
/214= "stimuli/as2_MNES_1_214_neg.jpg"
/215= "stimuli/as2_MNES_1_215_neg.jpg"
/216= "stimuli/as2_MNES_1_216_neg.jpg"
/217= "stimuli/as2_MNES_1_217_neg.jpg"
/218= "stimuli/as2_MNES_1_218_neg.jpg"
/219= "stimuli/as2_MNES_1_219_neg.jpg"
/220= "stimuli/as2_MNES_1_220_neg.jpg"
/221= "stimuli/as2_MNES_1_221_neg.jpg"
/222= "stimuli/as2_MNES_1_222_neg.jpg"
/223= "stimuli/as2_MNES_1_223_neg.jpg"
/224= "stimuli/as2_MNES_1_224_neg.jpg"
/225= "stimuli/as2_MNES_1_225_neg.jpg"
/226= "stimuli/as2_MNES_1_226_neg.jpg"
/227= "stimuli/as2_MNES_1_227_neg.jpg"
/228= "stimuli/as2_MNES_1_228_neg.jpg"
/229= "stimuli/as2_MNES_1_229_neg.jpg"
/230= "stimuli/as2_MNES_1_230_neg.jpg"
/231= "stimuli/as2_MNES_1_231_neg.jpg"
/232= "stimuli/as2_MNES_1_232_neg.jpg"
/233= "stimuli/as2_MNES_1_233_neg.jpg"
/234= "stimuli/as2_MNES_1_234_neg.jpg"
/235= "stimuli/as2_MNES_1_235_neg.jpg"
/236= "stimuli/as2_MNES_1_236_neg.jpg"
/237= "stimuli/as2_MNES_1_237_neg.jpg"
/238= "stimuli/as2_MNES_1_238_neg.jpg"
/239= "stimuli/as2_MNES_1_239_neg.jpg"
/240= "stimuli/as2_MNES_1_240_neg.jpg"
/241= "stimuli/as2_MNES_1_241_neg.jpg"
/242= "stimuli/as2_MNES_1_242_neg.jpg"
/243= "stimuli/as2_MNES_1_243_neg.jpg"
/244= "stimuli/as2_MNES_1_244_neg.jpg"
/245= "stimuli/as2_MNES_1_245_neg.jpg"
/246= "stimuli/as2_MNES_1_246_neg.jpg"
/247= "stimuli/as2_MNES_1_247_neg.jpg"
/248= "stimuli/as2_MNES_1_248_neg.jpg"
/249= "stimuli/as2_MNES_1_249_neg.jpg"
/250= "stimuli/as2_MNES_1_250_neg.jpg"
/251= "stimuli/as2_MNES_1_251_neg.jpg"
/252= "stimuli/as2_MNES_1_252_neg.jpg"
/253= "stimuli/as2_MNES_1_253_neg.jpg"
/254= "stimuli/as2_MNES_1_254_neg.jpg"
/255= "stimuli/as2_MNES_1_255_neg.jpg"
/256= "stimuli/as2_MNES_1_256_neg.jpg"
/257= "stimuli/as2_MNES_1_257_neg.jpg"
/258= "stimuli/as2_MNES_1_258_neg.jpg"
/259= "stimuli/as2_MNES_1_259_neg.jpg"
/260= "stimuli/as2_MNES_1_260_neg.jpg"
/261= "stimuli/as2_MNES_1_261_neg.jpg"
/262= "stimuli/as2_MNES_1_262_neg.jpg"
/263= "stimuli/as2_MNES_1_263_neg.jpg"
/264= "stimuli/as2_MNES_1_264_neg.jpg"
/265= "stimuli/as2_MNES_1_265_neg.jpg"
/266= "stimuli/as2_MNES_1_266_neg.jpg"
/267= "stimuli/as2_MNES_1_267_neg.jpg"
/268= "stimuli/as2_MNES_1_268_neg.jpg"
/269= "stimuli/as2_MNES_1_269_neg.jpg"
/270= "stimuli/as2_MNES_1_270_neg.jpg"
/271= "stimuli/as2_MNES_1_271_neg.jpg"
/272= "stimuli/as2_MNES_1_272_neg.jpg"
/273= "stimuli/as2_MNES_1_273_neg.jpg"
/274= "stimuli/as2_MNES_1_274_neg.jpg"
/275= "stimuli/as2_MNES_1_275_neg.jpg"
/276= "stimuli/as2_MNES_1_276_neg.jpg"
/277= "stimuli/as2_MNES_1_277_neg.jpg"
/278= "stimuli/as2_MNES_1_278_neg.jpg"
/279= "stimuli/as2_MNES_1_279_neg.jpg"
/280= "stimuli/as2_MNES_1_280_neg.jpg"
/281= "stimuli/as2_MNES_1_281_neg.jpg"
/282= "stimuli/as2_MNES_1_282_neg.jpg"
/283= "stimuli/as2_MNES_1_283_neg.jpg"
/284= "stimuli/as2_MNES_1_284_neg.jpg"
/285= "stimuli/as2_MNES_1_285_neg.jpg"
/286= "stimuli/as2_MNES_1_286_neg.jpg"
/287= "stimuli/as2_MNES_1_287_neg.jpg"
/288= "stimuli/as2_MNES_1_288_neg.jpg"
/289= "stimuli/as2_MNES_1_289_neg.jpg"
/290= "stimuli/as2_MNES_1_290_neg.jpg"
/291= "stimuli/as2_MNES_1_291_neg.jpg"
/292= "stimuli/as2_MNES_1_292_neg.jpg"
/293= "stimuli/as2_MNES_1_293_neg.jpg"
/294= "stimuli/as2_MNES_1_294_neg.jpg"
/295= "stimuli/as2_MNES_1_295_neg.jpg"
/296= "stimuli/as2_MNES_1_296_neg.jpg"
/297= "stimuli/as2_MNES_1_297_neg.jpg"
/298= "stimuli/as2_MNES_1_298_neg.jpg"
/299= "stimuli/as2_MNES_1_299_neg.jpg"
/300= "stimuli/as2_MNES_1_300_neg.jpg"
/301= "stimuli/as2_MNES_1_301_neg.jpg"
/302= "stimuli/as2_MNES_1_302_neg.jpg"
/303= "stimuli/as2_MNES_1_303_neg.jpg"
/304= "stimuli/as2_MNES_1_304_neg.jpg"
/305= "stimuli/as2_MNES_1_305_neg.jpg"
/306= "stimuli/as2_MNES_1_306_neg.jpg"
/307= "stimuli/as2_MNES_1_307_neg.jpg"
/308= "stimuli/as2_MNES_1_308_neg.jpg"
/309= "stimuli/as2_MNES_1_309_neg.jpg"
/310= "stimuli/as2_MNES_1_310_neg.jpg"
/311= "stimuli/as2_MNES_1_311_neg.jpg"
/312= "stimuli/as2_MNES_1_312_neg.jpg"
/313= "stimuli/as2_MNES_1_313_neg.jpg"
/314= "stimuli/as2_MNES_1_314_neg.jpg"
/315= "stimuli/as2_MNES_1_315_neg.jpg"
/316= "stimuli/as2_MNES_1_316_neg.jpg"
/317= "stimuli/as2_MNES_1_317_neg.jpg"
/318= "stimuli/as2_MNES_1_318_neg.jpg"
/319= "stimuli/as2_MNES_1_319_neg.jpg"
/320= "stimuli/as2_MNES_1_320_neg.jpg"
/321= "stimuli/as2_MNES_1_321_neg.jpg"
/322= "stimuli/as2_MNES_1_322_neg.jpg"
/323= "stimuli/as2_MNES_1_323_neg.jpg"
/324= "stimuli/as2_MNES_1_324_neg.jpg"
/325= "stimuli/as2_MNES_1_325_neg.jpg"
/326= "stimuli/as2_MNES_1_326_neg.jpg"
/327= "stimuli/as2_MNES_1_327_neg.jpg"
/328= "stimuli/as2_MNES_1_328_neg.jpg"
/329= "stimuli/as2_MNES_1_329_neg.jpg"
/330= "stimuli/as2_MNES_1_330_neg.jpg"
/331= "stimuli/as2_MNES_1_331_neg.jpg"
/332= "stimuli/as2_MNES_1_332_neg.jpg"
/333= "stimuli/as2_MNES_1_333_neg.jpg"
/334= "stimuli/as2_MNES_1_334_neg.jpg"
/335= "stimuli/as2_MNES_1_335_neg.jpg"
/336= "stimuli/as2_MNES_1_336_neg.jpg"
/337= "stimuli/as2_MNES_1_337_neg.jpg"
/338= "stimuli/as2_MNES_1_338_neg.jpg"
/339= "stimuli/as2_MNES_1_339_neg.jpg"
/340= "stimuli/as2_MNES_1_340_neg.jpg"
/341= "stimuli/as2_MNES_1_341_neg.jpg"
/342= "stimuli/as2_MNES_1_342_neg.jpg"
/343= "stimuli/as2_MNES_1_343_neg.jpg"
/344= "stimuli/as2_MNES_1_344_neg.jpg"
/345= "stimuli/as2_MNES_1_345_neg.jpg"
/346= "stimuli/as2_MNES_1_346_neg.jpg"
/347= "stimuli/as2_MNES_1_347_neg.jpg"
/348= "stimuli/as2_MNES_1_348_neg.jpg"
/349= "stimuli/as2_MNES_1_349_neg.jpg"
/350= "stimuli/as2_MNES_1_350_neg.jpg"
/351= "stimuli/as2_MNES_1_351_neg.jpg"
/352= "stimuli/as2_MNES_1_352_neg.jpg"
/353= "stimuli/as2_MNES_1_353_neg.jpg"
/354= "stimuli/as2_MNES_1_354_neg.jpg"
/355= "stimuli/as2_MNES_1_355_neg.jpg"
/356= "stimuli/as2_MNES_1_356_neg.jpg"
/357= "stimuli/as2_MNES_1_357_neg.jpg"
/358= "stimuli/as2_MNES_1_358_neg.jpg"
/359= "stimuli/as2_MNES_1_359_neg.jpg"
/360= "stimuli/as2_MNES_1_360_neg.jpg"
/361= "stimuli/as2_MNES_1_361_neg.jpg"
/362= "stimuli/as2_MNES_1_362_neg.jpg"
/363= "stimuli/as2_MNES_1_363_neg.jpg"
/364= "stimuli/as2_MNES_1_364_neg.jpg"
/365= "stimuli/as2_MNES_1_365_neg.jpg"
/366= "stimuli/as2_MNES_1_366_neg.jpg"
/367= "stimuli/as2_MNES_1_367_neg.jpg"
/368= "stimuli/as2_MNES_1_368_neg.jpg"
/369= "stimuli/as2_MNES_1_369_neg.jpg"
/370= "stimuli/as2_MNES_1_370_neg.jpg"
/371= "stimuli/as2_MNES_1_371_neg.jpg"
/372= "stimuli/as2_MNES_1_372_neg.jpg"
/373= "stimuli/as2_MNES_1_373_neg.jpg"
/374= "stimuli/as2_MNES_1_374_neg.jpg"
/375= "stimuli/as2_MNES_1_375_neg.jpg"
/376= "stimuli/as2_MNES_1_376_neg.jpg"
/377= "stimuli/as2_MNES_1_377_neg.jpg"
/378= "stimuli/as2_MNES_1_378_neg.jpg"
/379= "stimuli/as2_MNES_1_379_neg.jpg"
/380= "stimuli/as2_MNES_1_380_neg.jpg"
/381= "stimuli/as2_MNES_1_381_neg.jpg"
/382= "stimuli/as2_MNES_1_382_neg.jpg"
/383= "stimuli/as2_MNES_1_383_neg.jpg"
/384= "stimuli/as2_MNES_1_384_neg.jpg"
/385= "stimuli/as2_MNES_1_385_neg.jpg"
/386= "stimuli/as2_MNES_1_386_neg.jpg"
/387= "stimuli/as2_MNES_1_387_neg.jpg"
/388= "stimuli/as2_MNES_1_388_neg.jpg"
/389= "stimuli/as2_MNES_1_389_neg.jpg"
/390= "stimuli/as2_MNES_1_390_neg.jpg"
/391= "stimuli/as2_MNES_1_391_neg.jpg"
/392= "stimuli/as2_MNES_1_392_neg.jpg"
/393= "stimuli/as2_MNES_1_393_neg.jpg"
/394= "stimuli/as2_MNES_1_394_neg.jpg"
/395= "stimuli/as2_MNES_1_395_neg.jpg"
/396= "stimuli/as2_MNES_1_396_neg.jpg"
/397= "stimuli/as2_MNES_1_397_neg.jpg"
/398= "stimuli/as2_MNES_1_398_neg.jpg"
/399= "stimuli/as2_MNES_1_399_neg.jpg"
/400= "stimuli/as2_MNES_1_0_neg.jpg"
</item>


***********************************
***** Suspicion Probe 1
***********************************



<textbox suspicion1>
/ caption = "1. Beschreiben Sie in Ihren eigenen Worten, worum es Ihrer Meinung nach in dieser Studie geht."
/ multiline = true
/ required = false
/ textboxsize = (30%, 50%)
</textbox>

<textbox suspicion2>
/ caption = "2. Glaubten Sie zu irgendeinem Zeitpunkt, dass die Studie etwas anderes untersucht, als das, was Ihnen mitgeteilt wurde?"
/ multiline = true
/ required = false
/ textboxsize = (30%, 20%)
</textbox>

<textbox suspicion3>
/ caption = "3. Beeinflusste dies Ihr Verhalten in irgendeiner Weise?"
/ multiline = true
/ required = false
/ textboxsize = (30%, 20%)
</textbox>

<textbox suspicion4>
/ caption = "4. Hatten Sie den Eindruck, dass bestimmte Reaktionen von Ihnen erwartet wurden?"
/ multiline = true
/ required = false
/ textboxsize = (30%, 20%)
</textbox>

<textbox suspicion5>
/ caption = "5. Welchen Zweck haben wir Ihrer Meinung nach mit der Beschreibung von David verfolgt?"
/ multiline = true
/ required = false
/ textboxsize = (30%, 20%)
</textbox>

<textbox suspicion6>
/ caption = "6. Welche Information zu David hielten Sie für relevant in Bezug auf die Studie?"
/ multiline = true
/ required = false
/ textboxsize = (30%, 20%)
</textbox>

<surveypage suspicion1>
/ caption = "Bevor wir Ihnen einige Fragen zu dem gelesenen Text stellen, möchten wir Sie um Feedback zu dem bisherigen Teil der Studie bitten. Wir möchten sicherstellen, dass der Aufbau der Studie stimmig ist und benötigen Ihre Rückmeldung, um uns bei der Verbesserung dieser Studie zu helfen. Bitte beantworten Sie die folgenden Fragen so ehrlich wie möglich. Ihre Antworten sind äußerst wichtig für die wissenschaftliche Gültigkeit dieser Studie. Antworten Sie bitte so ausführlich, wie es Ihrer Meinung nach notwendig ist, um die jeweilige Frage vollständig zu beantworten."
/ questions = [1=suspicion1]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<surveypage suspicion2>
/ caption = ""
/ questions = [1=suspicion2; 2=suspicion3; 3=suspicion4]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<surveypage suspicion3>
/ caption = ""
/ questions = [1=suspicion5; 2=suspicion6]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<block suspicion1>
/ trials = [1=suspicion1; 2=suspicion2; 3=suspicion3]
</block>




***********************************
***** Free Recall David
***********************************


<textbox mc_open>
/ caption = "Bitte beschreiben Sie David kurz in eigenen Worten."
/ multiline = true
/ required = false
/ textboxsize = (30%, 50%)
</textbox>

<surveypage mc_open>
/ caption = "Vielen Dank für Ihr Feedback! Es folgen nun einige Fragen zu David und dem gelesenen Text."
/ questions = [1=mc_open]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<block mc_open>
/ trials = [1=mc_open]
</block>


***********************************
***** Explizites Rating David
***********************************

<page david_fragen>
^^Bitte versuchen Sie nun, David anhand der Ihnen vorgegebenen Charaktereigenschaften einzuschätzen.
^^Es gibt hier keine richtigen und falschen Antworten, sondern nur Ihren persönlichen Eindruck, den Sie von David bekommen haben.
^^Klicken Sie bitte diejenige Antwort an, die Ihrer Meinung nach am ehesten auf David zutrifft. 
^^Wählen Sie die „1“, wenn die Antwort „überhaupt nicht“ zutrifft und die „5“, wenn sie „sehr stark“ zutrifft. Nutzen Sie die Optionen dazwischen, um Ihr Urteil abzustufen. 
</page>

<text david_fragen>
/items = david_fragen
/ fontstyle = ("Arial", 4%)
/ select = sequence
/ position = (50,50)
</text>

<text davidreminder>
/ halign = left
/ fontstyle = ("Arial", 3%)
/ items = ("Inwiefern trifft die folgende Eigenschaft auf David zu?")
/ position = (10,20)
</text>

<item david_fragen>
/	1	=	"selbstsicher"
/	2	=	"einsam"
/	3	=	"intelligent"
/	4	=	"warm"
/	5	=	"phantasievoll"
/	6	=	"aufrichtig"
/	7	=	"wissbegierig"
/	8	=	"freundlich"
/	9	=	"lebhaft"
/	10	=	"gesetzestreu "
/	11	=	"kompetent"
/	12	=	"gutmütig"
/	13	=	"besorgt "
/	14	=	"tüchtig"
/	15	=	"gesellig "
/	16	=	"ehrlich"
/	17	=	"ängstlich"
/	18	=	"unabhängig"
/	19	=	"ruhig "
/	20	=	"vertrauenswürdig"
</item>



<likert david_fragen>
/ stimulustimes = [1=david_fragen]
/ anchors = [1="gar nicht"; 2=""; 3=""; 4=""; 5="sehr"]
/ anchorwidth = 180
/ numpoints = 5
/ fontstyle = ("Arial", 2%)
/ position = (50, 70)
/ mouse=true
</likert>

<block david_fragen>
/ bgstim = (davidreminder)
/ preinstructions = (david_fragen)
/ trials = [1-20 = david_fragen]
</block>







******************************************************
********** Manipulation Check *****************
******************************************************



<radiobuttons mc_a>
/ caption = "1. David lebt in"
/ options = ("Dortmund", "Düsseldorf","Dormagen","Detmold")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_b>
/ caption = "2. David hält Vorträge zu"
/ options = ("Kindererziehung", "seiner Arbeit in der Künstleragentur","jüdischer Musik","Umweltschutz")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_c>
/ caption = "3. David hat studiert:"
/ options = ("Jura", "BWL","Musik","Politik")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_d>
/ caption = "4. David arbeitet ehrenamtlich in einer Organisation für"
/ options = ("Opferschutz", "die Bewahrung des Waldes","Nachkommen von Holocaustüberlebenden","krebskranke Kinder")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>


<radiobuttons mc_e>
/ caption = "5. David lebt in"
/ options = ("einer Wohnung", "einer Waldhütte","einem Haus","einer Wohngemeinschaft")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_f>
/ caption = "6. David ist"
/ options = ("Moslem", "Christ","Jude","Buddhist")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_g>
/ caption = "7. Davids Aufgabe im Hilfsprojekt ist"
/ options = ("Spenden verwalten", "Informationsabende organisieren","Gitarre spielen","Info-Material gestalten")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_h>
/ caption = "8. David spielt"
/ options = ("Gitarre", "Bass","Geige","Klarinette")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_i>
/ caption = "9. Davids Sohn heißt"
/ options = ("Stefan", "Sven","Simon","Sebastian")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons mc_j>
/ caption = "10. David engagiert sich"
/ options = ("in der Kirche", "im Fußballverein","in der Synagoge","im Kindergarten")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>


<surveypage mc_1>
/ caption = "Bitte erinnern Sie sich nun an den Text über David und wählen Sie zu jeder Aussage die richtige Option aus."
/ questions = [1=mc_a; 2=mc_b; 3=mc_c; 4=mc_d]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2.5%, true)
/ itemfontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<surveypage mc_2>
/ caption = ""
/ questions = [1=mc_e; 2=mc_f; 3=mc_g; 4=mc_h]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<surveypage mc_3>
/ caption = ""
/ questions = [1=mc_i; 2=mc_j]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<block mc>
/ trials = [1=mc_1; 2=mc_2; 3=mc_3]
</block>




**********************************************************************************************************************************************************************
**********************************************************************************************************************************************************************
	demog & religion
**********************************************************************************************************************************************************************
**********************************************************************************************************************************************************************
<page demog>
^^Vielen Dank! Hiermit ist der Hauptteil der Studie abgeschlossen.
^^Zum Schluss möchten wir Sie auf den folgenden Seiten bitten, einige Angaben zu Ihrer Person zu machen sowie Fragen zu Ihren Einstellungen zu beantworten.
</page>


** demog.

<textbox age>
/ caption = "Alter:"
/ required = false
</textbox>

<radiobuttons sex>
/ caption = "Geschlecht:"
/ options = ("weiblich", "männlich")
/ optionvalues = ("1", "2")
/ orientation = horizontal
</radiobuttons>

<radiobuttons bildung>
/ caption = "Bildungsabschluss:"
/ options = ("Hauptschule", "Realschule", "Gymnasium", "Universität", "keiner")
/ optionvalues = ("1", "2", "3", "4", "0", "9")
/ other = "sonstiger:"
</radiobuttons>

<textbox fach>
/ caption = "Studienfach bzw. Beruf"
/ required = false
</textbox>

<radiobuttons migration>
/ caption = "Haben Sie einen Migrationshintergrund?"
/ options = ("ja", "nein")
/ optionvalues = ("1", "0")
/ orientation = horizontal
</radiobuttons>

<textbox migration2>
/ caption = "Falls ja, aus welchem Land?"
/ required = false
</textbox>

<radiobuttons religion>
/ caption = "Welcher Religion sind Sie angehörig?"
/ options = ("Chr. Katholisch", "Chr. Evangelisch", "Muslimisch", "Jüdisch", "keiner")
/ optionvalues = ("1", "2", "3", "4", "0", "9")
/ other = "andere:"
</radiobuttons>



<surveypage demog1>
/ caption = "Um beschreiben zu können, wer an dieser Studie teilgenommen hat, möchten wir Sie bitten, einige Angaben zu Ihrer Person zu machen."
/ questions = [1=age; 2=sex; 3=bildung; 4=fach]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%, true)
/ responsefontstyle = ("Arial", 1.5%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ txcolor = black
/ showquestionnumbers = false
</surveypage>

<surveypage demog2>
/ caption = ""
/ questions = [1=migration; 2=migration2; 3=religion]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%, true)
/ responsefontstyle = ("Arial", 1.5%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ txcolor = black
/ showquestionnumbers = false
</surveypage>

<block demog>
/ preinstructions = (demog)
/ trials = [1=demog1; 2=demog2]
</block>






****************************************************************************
*********************Antisemitismus-Skala****************************
****************************************************************************
<page as>
^^Im Folgenden erhalten Sie einige Aussagen zum deutsch-jüdischen Verhältnis.
Es geht dabei um Aussagen bezüglich des Blicks auf die Vergangenheit, ebenso wie Fragen zum heutigen Verhältnis.
Wir wollen an dieser Stelle noch einmal betonen, dass Ihre Antworten komplett anonym bleiben und Sie erneut bitten, so ehrlich wie möglich zu antworten.
Es gibt keine richtigen oder falschen Antworten, sondern lediglich Ihre ganz persönliche Meinung.
^^Um uns diese mitzuteilen können Sie Ihre Zustimmung zu jeder Aussage auf einer Skala von 1 (Diese Aussage lehne ich voll und ganz ab) bis 7 (Dieser Aussage stimme ich voll und ganz zu) abstufen.
</page>

<item as>
/	1	=	"Das Verhältnis zwischen Deutschen und Juden ist nach wie vor geprägt von den Spuren der Vergangenheit."
/	2	=	"Sollte die von mir präferierte Partei einen Kandidaten nominieren, der Jude ist, wäre ich damit einverstanden, dass ein Jude deutscher Kanzler wird."
/	3	=	"Die Juden besitzen wieder zuviel Macht und Einfluss in der Welt."
/	4	=	"Juden haben viel zum deutschen kulturellen Leben beigetragen."
/	5	=	"Bei der Politik, die Israel macht, kann ich gut verstehen, dass man etwas gegen Juden hat."
/	6	=	"Die Juden nutzen die Erinnerung an den Holocaust heute für ihren eigenen Vorteil aus."
/	7	=	 "Ich kann mich leicht schuldig fühlen für die negativen Folgen, die durch Deutsche veranlasst wurden."
/	8	=	"Viele Juden versuchen, aus der Vergangenheit des Dritten Reiches heute ihren Vorteil zu ziehen."
/	9	=	"Manchmal habe ich das Gefühl, dass die Juden unser schlechtes Gewissen ausnutzen."
/	10	=	"Durch die israelische Politik werden mir die Juden immer unsympathischer."
/	11	=	"Die Juden sollten aufhören, sich ständig darüber zu beschweren, was ihnen in Nazi-Deutschland widerfahren ist."
/	12	=	"Juden sorgen mit ihren Ideen immer für Unfrieden."
/	13	=	 "Juden werden in Deutschland als unantastbare Moralinstitution gesehen."
/	14	=	"Oft wird zuviel auf jüdisches Leid im 2. Weltkrieg geschaut und vergessen, dass es auch andere Opfer gab."
</item>

<likert as>
/ fontstyle = ("Arial", 1.5%)
/ anchors = [1="stimme überhaupt nicht zu"; 7="stimme voll und ganz zu"]
/ anchorwidth = 10% 
/ position = (50,70)
/ stimulustimes = [1=as]
/ numpoints = 7
/ mouse = true
</likert>

<text as>
/items = as
/ fontstyle = ("Arial", 3%)
/ select = sequence
/ size = (60%, 30%)
/ position = (50,50)
</text>

<block as>
/ preinstructions = (as)
/ trials =  [1-14=as]
</block>



******************************************************
********** Nachbefragung *****************
******************************************************

<textbox nachbefragung1>
/ caption = "Beschreiben Sie in Ihren eigenen Worten, worum es Ihrer Meinung nach in dieser Studie geht."
/ multiline = true
/ required = false
/ textboxsize = (30%, 50%)
</textbox>

<textbox nachbefragung2>
/ caption = "Manchmal hören Personen etwas über eine Studie bevor sie an dieser teilnehmen. Hatten Sie irgendwelche Informationen über diese Studie bevor Sie teilnahmen, aus welcher Quelle auch immer (z.B. von anderen Teilnehmern, aus Studien an denen Sie zuvor teilgenommen haben, aus dem Studium)? Falls ja, beschreiben Sie bitte, welche Informationen Sie zuvor hatten (Wir interessieren uns nicht dafür, wie oder von wem die Informationen erhalten wurden)."
/ multiline = true
/ required = false
/ textboxsize = (30%, 50%)
</textbox>




<surveypage nachbefragung1>
/ caption = "Manchmal ändert sich während der Teilnahme an einer Studie der Eindruck, den man von dieser Studie hat. Daher möchten wir Sie zum Abschluss nochmals um Ihre Rückmeldung zu dieser Studie bitten."
/ questions = [1=nachbefragung1]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ showquestionnumbers = false
/ showpagenumbers = false
/ fontstyle = ("Arial", 2%)
/ nextbuttonposition = (90,90) 
</surveypage>

<surveypage nachbefragung2>
/ caption = ""
/ questions = [1=nachbefragung2]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ showquestionnumbers = false
/ showpagenumbers = false
/ fontstyle = ("Arial", 2%)
/ nextbuttonposition = (90,90) 
</surveypage>



<block nachbefragung>
/ trials = [1=nachbefragung1; 2=nachbefragung2]
</block>
