cat("==== START environment (status: OK) ====\n")
cat(R.version.string, "\n")
cat("platform:", R.version$platform, "\n")
cat("RNGkind:", RNGkind()[1], "\n")
cat("Packages loaded: survival, nnet, MASS (base + recommended availability check)\n")
cat("survival available:", requireNamespace("survival", quietly=TRUE), "\n")
cat("nnet available:", requireNamespace("nnet", quietly=TRUE), "\n")
cat("MASS available:", requireNamespace("MASS", quietly=TRUE), "\n")
cat("==== END environment (status: OK) ====\n")
