options(width=200)
setwd("C:/Users/lroesele.IVV5NET/Claude_Code/ReproAI/Meta Psychology/Volume 3 (2019)/02_KuperBott_MoralLicensing/ReproAI/KuperBott_MoralLicensing_878/R")
dat <- read.table("dat_new_s.txt", sep=" ", header=TRUE, fileEncoding="latin1")
cat("rows =", nrow(dat), "\n\n")
cat("=== unique authors (raw, with leading chars) ===\n")
for (a in sort(unique(dat$authors))) cat("  [", a, "]\n", sep="")
cat("\n=== rows per author ===\n")
tab <- table(dat$authors)
print(tab)
cat("\n=== world_region table ===\n")
print(table(dat$world_region, useNA="ifany"))
cat("\n=== comparison table ===\n")
print(table(dat$comparison, useNA="ifany"))
cat("\n=== N range: min", min(dat$N, na.rm=TRUE), "max", max(dat$N, na.rm=TRUE), "===")
cat("\n=== any NA in yi/se? ===\n")
cat("NA yi:", sum(is.na(dat$yi)), " NA se:", sum(is.na(dat$se)), "\n")
cat("\n=== check dat_new_b (the 'big' / blanken?) ===\n")
b <- read.table("dat_new_b.txt", sep=" ", header=TRUE, fileEncoding="latin1")
cat("dat_new_b rows =", nrow(b), "\n")
cat("dat_new_b cols:", paste(names(b), collapse=", "), "\n")
cat("\n=== dat_old_s ===\n")
os <- read.table("dat_old_s.txt", sep=" ", header=TRUE, fileEncoding="latin1")
cat("dat_old_s rows =", nrow(os), " cols:", paste(names(os), collapse=", "), "\n")
cat("\n=== dat_old_b ===\n")
ob <- read.table("dat_old_b.txt", sep=" ", header=TRUE, fileEncoding="latin1")
cat("dat_old_b rows =", nrow(ob), " cols:", paste(names(ob), collapse=", "), "\n")
cat("DONE\n")
