import os, csv, json
from datetime import date

BASE = r"C:\Users\lroesele.IVV5NET\Claude_Code\ReproAI\Nature Human Behavior"

def generate_meta_report(year, findings, output_path):
    total = len(findings)
    p1 = sum(1 for f in findings if f['severity'] == 'P1')
    p2 = sum(1 for f in findings if f['severity'] == 'P2')
    p3 = sum(1 for f in findings if f['severity'] == 'P3')
    ok = sum(1 for f in findings if f['status'] == 'ok')
    warn = sum(1 for f in findings if f['status'] == 'warn')
    critical = sum(1 for f in findings if f['status'] == 'critical')
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>NHB Volume {year} - ReproAI Meta-Report</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 2em; max-width: 1200px; }}
h1 {{ color: #1a1a2e; }}
.stats {{ display: flex; gap: 2em; margin: 2em 0; }}
.stat {{ background: #f0f0f5; padding: 1em; border-radius: 8px; min-width: 150px; }}
.stat .num {{ font-size: 2em; font-weight: bold; }}
.stat .label {{ color: #666; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
th, td {{ border: 1px solid #ddd; padding: 0.5em; text-align: left; }}
th {{ background: #1a1a2e; color: white; }}
tr:nth-child(even) {{ background: #f9f9f9; }}
.severity-P1 {{ color: #e74c3c; font-weight: bold; }}
.severity-P2 {{ color: #f39c12; font-weight: bold; }}
.severity-P3 {{ color: #27ae60; }}
.status-ok {{ color: #27ae60; }}
.status-warn {{ color: #f39c12; }}
.status-critical {{ color: #e74c3c; font-weight: bold; }}
</style>
</head>
<body>
<h1>Nature Human Behavior Volume {year} - ReproAI Meta-Report</h1>
<p>Audit Date: {date.today().isoformat()}</p>
<p>Engine: anomalyco/opencode | Rules: REPRO_STANDARDS.md</p>

<h2>Summary Statistics</h2>
<div class="stats">
<div class="stat"><div class="num">{total}</div><div class="label">Empirical Papers</div></div>
<div class="stat"><div class="num">{p1}</div><div class="label">P1 (Critical)</div></div>
<div class="stat"><div class="num">{p2}</div><div class="label">P2 (Moderate)</div></div>
<div class="stat"><div class="num">{p3}</div><div class="label">P3 (Minor)</div></div>
</div>

<h2>Findings by Severity</h2>
<table>
<tr><th>Severity</th><th>Count</th><th>Description</th></tr>
<tr><td class="severity-P1">P1</td><td>{p1}</td><td>No data/code availability statement</td></tr>
<tr><td class="severity-P2">P2</td><td>{p2}</td><td>Availability stated but no direct link</td></tr>
<tr><td class="severity-P3">P3</td><td>{p3}</td><td>Data/code available with direct link</td></tr>
</table>

<h2>Findings by Status</h2>
<table>
<tr><th>Status</th><th>Count</th></tr>
<tr><td class="status-ok">OK</td><td>{ok}</td></tr>
<tr><td class="status-warn">WARN</td><td>{warn}</td></tr>
<tr><td class="status-critical">CRITICAL</td><td>{critical}</td></tr>
</table>

<h2>Detailed Findings</h2>
<table>
<tr><th>Paper</th><th>Author</th><th>Title</th><th>Severity</th><th>Status</th><th>Message</th><th>Links</th></tr>
"""
    
    for f in findings:
        html += f"""<tr>
<td>{f['num']}</td>
<td>{f['first_author']}</td>
<td>{f['title'][:60]}</td>
<td class="severity-{f['severity']}">{f['severity']}</td>
<td class="status-{f['status']}">{f['status']}</td>
<td>{f['message'][:100]}</td>
<td>{f['links'][:80]}</td>
</tr>
"""
    
    html += """</table>
<p><em>This report was generated by ReproAI using static analysis of article metadata and HTML content.</em></p>
</body>
</html>"""
    
    with open(output_path, 'w', encoding='utf-8') as fp:
        fp.write(html)
    print(f"Generated: {output_path}")

# Load findings
for year in ['2019', '2020']:
    csv_path = os.path.join(BASE, f"VOLUME_{year}_REPROAI_SUMMARY.csv")
    with open(csv_path, encoding='utf-8') as f:
        findings = list(csv.DictReader(f))
    
    output_path = os.path.join(BASE, f"VOLUME_{year}_REPROAI_META_REPORT.html")
    generate_meta_report(year, findings, output_path)
