## ReproAI environment / provenance record (re-audit 2026-09-14, DeepSeek V4 Flash via uniGPT)
sink(file = "C:/Users/lroesele.IVV5NET/Claude_Code/ReproAI/Meta Psychology/Volume 4 (2020)/03_Brunner_PowerHeterogeneity/ReproAI/Brunner_PowerHeterogeneity_874/exec_check/output/_environment.txt")
cat("==== START (status: OK) ====\n")
cat("R version: ", R.version.string, "\n", sep="")
cat("RNGkind: ", paste(RNGkind(), collapse=","), "\n", sep="")
cat("Platform: ", .Platform$OS.type, "/", .Platform$r_arch, "\n", sep="")
cat("Locale: ", Sys.getlocale("LC_CTYPE"), "\n", sep="")
cat("Working dir: ", getwd(), "\n", sep="")
cat("Date: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n", sep="")
cat("sessionInfo:\n")
print(sessionInfo())
cat("\nStandard R packages (base install, no non-base needed for these checks).\n")
cat("==== END (status: OK) ====\n")
sink()
cat("env written\n")
