suppressMessages({ library(readr); library(dplyr) })
setwd("C:/Users/lroesele.IVV5NET/Claude_Code/ReproAI/Meta Psychology/Volume 3 (2019)/09_deLeeuw_ERP/ReproAI/deLeeuw_ERP_1481/exec_check")
beh <- read_csv("data/generated/beh_data_tidy.csv", show_col_types=FALSE)
excl <- c(8,21,11,23,25,40)
all_ids <- unique(beh$subject_id)
cat("class:", class(beh$subject_id), "\n")
A <- beh %>% filter(!subject_id %in% excl)
survive <- unique(A$subject_id)
removed_author <- setdiff(all_ids, survive)
cat("removed by author-style (character) filter:\n"); print(sort(as.integer(removed_author)))
B <- beh %>% mutate(sid=as.integer(subject_id)) %>% filter(!sid %in% excl)
survive2 <- unique(B$sid)
removed_proper <- setdiff(sort(unique(as.integer(all_ids))), sort(survive2))
cat("removed by proper integer filter:\n"); print(removed_proper)
m <- match(beh$subject_id, as.character(excl))
cat("subject_ids matching as.character(excl):\n"); print(unique(beh$subject_id[!is.na(m)]))
