d <- read.csv("C:/Users/lroesele.IVV5NET/AppData/Local/Temp/opencode/reprochecks/reproai_run2/17_Aung_voice/iPodStudyData.csv", stringsAsFactors=FALSE)
cat("rows", nrow(d), "\n")
cat("countries", length(unique(d$country)), "\n")
cat("id", length(unique(d$id)), "\n")
cat("voice", length(unique(d$voice)), "\n")
print(table(d$question))
cat("\npair\n")
print(table(d$Pair))
cat("\nregions\n")
print(table(d$Region))
cat("\nsex\n")
print(table(d$sex))
cat("\nOutcome table\n")
print(table(d$Outcome))
cat("\ncolumns with RelationalMobility/localRM\n")
print(head(d[, c("country","Region","localRM","Outcome","question")]))
