suppressMessages({library(afex);library(car);library(dplyr);library(reshape2);library(plyr);library(sjstats)})
analysis_path <- "C:/Users/LROESE~1.IVV/AppData/Local/Temp/opencode/repro_pilot/work/2019-63/Study4-Control/ANALYSIS/R"
setwd(analysis_path)
PAV <- read.delim(file.path(analysis_path,'Database-PAVcontrol.txt'), header=T, sep='')
PAV$ID<-factor(PAV$ID);PAV$CS_VAL<-factor(PAV$CS_VAL);PAV$congr_SIDE<-factor(PAV$congr_SIDE)
VALUE<-subset(PAV, CS_VAL=='CSp'|CS_VAL=='CSc')
cat("===== DWELL TIME (CS+ vs CS control) =====\n")
vars<-names(VALUE)%in%c('ID','CS_VAL','ANT_DW_congr');vn<-na.omit(VALUE[vars]);vm<-aggregate(vn$ANT_DW_congr,by=list(vn$ID,vn$CS_VAL),FUN='mean');colnames(vm)<-c('ID','CS_VAL','ANT_DW_congr')
fit<-aov(ANT_DW_congr~CS_VAL+Error(ID/CS_VAL),data=vm);print(anova_stats(fit$`ID:CS_VAL`))
cat("===== PUPIL (CS+ vs CS control) =====\n")
vars<-names(VALUE)%in%c('ID','CS_VAL','CS_pupil');pn<-na.omit(VALUE[vars]);pm<-aggregate(pn$CS_pupil,by=list(pn$ID,pn$CS_VAL),FUN='mean');colnames(pm)<-c('ID','CS_VAL','CS_pupil')
fit<-aov(CS_pupil~CS_VAL+Error(ID/CS_VAL),data=pm);print(anova_stats(fit$`ID:CS_VAL`))
cat("===== RT congr_SIDE =====\n")
rm<-aggregate(US_RT~ID*congr_SIDE,data=PAV,FUN=mean,na.action=na.omit);fit<-aov(US_RT~congr_SIDE+Error(ID/(congr_SIDE)),data=rm);print(anova_stats(fit$`ID:congr_SIDE`))
cat("===== LIKING CSp vs CSc =====\n")
LK<-aggregate(ratings~ID*CS_VAL,data=PAV,FUN=mean,na.action=na.pass);LK$c[LK$CS_VAL=='CSm']<-0;LK$c[LK$CS_VAL=='CSc']<-1;LK$c[LK$CS_VAL=='CSp']<- -1;LK1<-subset(LK,c!=0)
fit<-aov(ratings~c+Error(ID/(c)),data=LK1);print(anova_stats(fit$`ID:c`))
cat("===== LIKING CSp vs CSm =====\n")
LK$c2[LK$CS_VAL=='CSm']<- -1;LK$c2[LK$CS_VAL=='CSc']<-0;LK$c2[LK$CS_VAL=='CSp']<-1;LK2<-subset(LK,c2!=0)
fit<-aov(ratings~c2+Error(ID/(c2)),data=LK2);print(anova_stats(fit$`ID:c2`))
cat("===== LIKING CSc vs CSm =====\n")
LK$c3[LK$CS_VAL=='CSm']<- -1;LK$c3[LK$CS_VAL=='CSc']<-1;LK$c3[LK$CS_VAL=='CSp']<-0;LK3<-subset(LK,c3!=0)
fit<-aov(ratings~c3+Error(ID/(c3)),data=LK3);print(anova_stats(fit$`ID:c3`))
