** Gruppen:
1: jüdisch / reparationsforderung
2: christlich / reparationsforderung
3: jüdisch / bewahrung von waldgebieten
4: christlich / bewahrung von waldgebieten





<expt >
/ blocks = [	1 = intro;
				2 = david;
				3 = panas;
				4 = facial_davids;
				5 = suspicion1;
				6 = david_fragen;
				7 = wsc;
				8 = mc;
				9 = demog;
				10 = comment]
</expt>


<variables>
/ group = (1 of 4) (david_text = david1)
/ group = (2 of 4) (david_text = david2)
/ group = (3 of 4) (david_text = david3)
/ group = (4 of 4) (david_text = david4)
/ groupassignment = subjectnumber
</variables>




<data>
/ columns = [date, time, subject, variables.currentgroupnumber, blockcode, blocknum, trialcode, trialnum, response, correct, latency, stimulusnumber, stimulusitem, stimulusnumber, stimulusitem, stimulusnumber, stimulusitem]
</data>

<defaults>
/ screencolor = (255, 255, 255)
/ txbgcolor = (255, 255, 255)
/ fontstyle = ("Arial", 3%, false, false, false, false, 5, 0)
/ endlock = true("Vielen Dank für Ihre Teilnahme!") 
/ valign = center
/ halign =center
</defaults>

<instruct>
/ inputdevice = mouse
/ nextlabel = "Weiter"
/ lastlabel = "Weiter"
/ fontstyle = ("Arial", 2%)
/ windowsize=(98%,95%)
</instruct>

*********************INTRO**********************
***************************************************

<picture logo>
/ items = ("humfak_leiste.jpg")
/ position = (50,10)
</picture>

<text introtext1>
/ fontstyle = ("Arial", 3%, false, false, true)
/ items = ("S O C I A L     C O G N I T I O N     C O L O G N E")
/ position = (50, 20)
</text>

<text introtext2>
/ fontstyle = ("Arial", 5%)
/ items = ("Herzlich Willkommen!")
/ position = (50, 40)
</text>


<text intronext>
/ fontstyle = ("Arial", 3%)
/ items = ("Drücken Sie eine beliebige Taste um zu beginnen.")
/ position = (50, 80)
</text>

<trial intro>
/ stimulustimes = [0=logo, introtext1, introtext2; 500=intronext]
/ validresponse = (anyresponse)
</trial>




<page start>
^^Herzlich Willkommen und Danke für Ihre Teilnahme!
^^Bevor Sie beginnen, lesen Sie bitte die folgenden Informationen zu dieser Studie.

^^In dieser Studie interessieren wir uns dafür, wie wir andere Menschen wahrnehmen und wie wir uns an diese erinnern.
Sie werden im Folgenden gebeten, sich einen Eindruck von einer Person zu bilden, verschiedene Fragebogen zu beantworten sowie eine Bildklassifikationsaufgabe zu bearbeiten.
Zwischen den einzelnen Teilen dieser Studie werden wir Sie bitten, eine kurze Vorstudie zur Erstellung von Untersuchungsmaterial für zukünftige Forschungsprojekte zu bearbeiten.
Insgesamt wird die Teilnahme etwa 25 bis 30 Minuten dauern.

^^Die Teilnahme an dieser Studie ist freiwillig. Weiterhin werden alle in dieser Studie erhobenen Daten anonym gespeichert.
Es ist daher unmöglich Untersuchungsteilnehmer rückwirkend zu identifizieren.
Die Daten werden nicht individuell, sondern nur über alle TeilnehmerInnen hinweg ausgewertet. 

^^Sie haben das Recht, die Teilnahme jederzeit ohne Angabe von Gründen abzubrechen, ohne dass Ihnen dadurch Nachteile entstehen.
Der Anspruch auf Vergütung entfällt in diesem Fall jedoch.

^^Nach Abschluss der Studie werden wir Sie gerne über die wissenschaftliche Fragestellung und die Ziele der Untersuchung vollständig aufklären, sofern Sie dies wünschen.

^^^^Wenn Sie die oben stehenden Informationen über die Studie gelesen haben und bereit sind, daran teilzunehmen, klicken Sie bitte auf WEITER, um zu beginnen.
^^Falls Sie nicht teilnehmen möchten oder die Untersuchung abbrechen möchten, wenden Sie sich bitte an die Versuchsleitung.
</page>


<block intro>
/trials = [1=intro]
/ postinstructions = (start)
</block>




********************************
********** Target: David ***
********************************

<picture weiter>
/ items = ("weiter.jpg")
/ position = (90,90)
</picture>

<text david_instr>
/ items = ("Bilden Sie sich bitte einen ersten Eindruck von der geschilderten Person")
/ fontstyle = ("Arial", 3%, true)
/ position = (50,10)
/ valign = bottom
</text>


<text face_instr>
/ fontstyle = ("Arial", 2%)
/ items = ("Ihnen wird im Folgenden eine Person vorgestellt. Zuerst werden Sie kurz das Gesicht der Person gezeigt bekommen. Danach werden Sie einen kurzen Text über die Person lesen. Bilden Sie sich bitte einen ersten Eindruck von der geschilderten Person. Wir werden Ihnen später Fragen zu dieser Person stellen.~n~n
Wenn Sie bereit sind, klicken Sie auf ~"Weiter~", um das Gesicht anzuzeigen. ~n~nNach 10 Sekunden geht es dann automatisch weiter zum Text.")
/ position = (50,20)
/ size = (50%,70%)
/ hjustify = left
/ valign = top
</text>

<trial face_instr>
/ stimulustimes = [0 = david_instr, face_instr, weiter]
/ inputdevice = mouse
/ validresponse = (weiter)
</trial>


<picture david_pic>
/ items = ("base_face.jpg")
</picture>

<trial david_pic>
/ stimulustimes = [0 = david_pic]
/ response = timeout(10000)
/ validresponse = (noresponse)
</trial>



<text david>
/ fontstyle = ("Arial", 2%)
/ hjustify = left
/ items = david_text
/ size = (50%, 70%)
/ position = (50,20)
/ valign = top
</text>

<item david1>
/1 = "David S. arbeitet als Abteilungsleiter in einer großen Firma in Frankfurt am Main. Er beginnt seinen Arbeitstag meist gegen 8:30 Uhr und beendet ihn um 18 Uhr, freitags macht er etwas früher Schluss.~n~n
Aufgrund seiner beruflichen Erfahrung wurde er schon mehrfach gefragt, ob er sich vorstellen könnte, im Gemeinderat der örtlichen Synagoge mitzuarbeiten, in dem auch sein Vater tätig ist. Bislang hat er sich jedoch dagegen entschieden.~n~n
In seiner Freizeit treibt er zweimal die Woche Sport, liest viel und engagiert sich in einer Organisation, die sich für Entschädigungszahlungen an noch lebende ehemalige jüdische KZ-Insassen einsetzt.~n~n
Gesundheitlich geht es David S. gut. Außer einem geringfügig erhöhten Blutdruck hat er keinerlei Beschwerden. Er lebt alleine in einer geräumigen Dachgeschosswohnung."
</item>

<item david2>
/1 = "David S. arbeitet als Abteilungsleiter in einer großen Firma in Frankfurt am Main. Er beginnt seinen Arbeitstag meist gegen 8:30 Uhr und beendet ihn um 18 Uhr, freitags macht er etwas früher Schluss.~n~n
Aufgrund seiner beruflichen Erfahrung wurde er schon mehrfach gefragt, ob er sich vorstellen könnte, im Gemeinderat der örtlichen Kirchengemeinde mitzuarbeiten, in dem auch sein Vater tätig ist. Bislang hat er sich jedoch dagegen entschieden.~n~n
In seiner Freizeit treibt er zweimal die Woche Sport, liest viel und engagiert sich in einer Organisation, die sich für Entschädigungszahlungen an noch lebende ehemalige jüdische KZ-Insassen einsetzt.~n~n
Gesundheitlich geht es David S. gut. Außer einem geringfügig erhöhten Blutdruck hat er keinerlei Beschwerden. Er lebt alleine in einer geräumigen Dachgeschosswohnung."
</item>

<item david3>
/1 = "David S. arbeitet als Abteilungsleiter in einer großen Firma in Frankfurt am Main. Er beginnt seinen Arbeitstag meist gegen 8:30 Uhr und beendet ihn um 18 Uhr, freitags macht er etwas früher Schluss.~n~n
Aufgrund seiner beruflichen Erfahrung wurde er schon mehrfach gefragt, ob er sich vorstellen könnte, im Gemeinderat der örtlichen Synagoge mitzuarbeiten, in dem auch sein Vater tätig ist. Bislang hat er sich jedoch dagegen entschieden.~n~n
In seiner Freizeit treibt er zweimal die Woche Sport, liest viel und engagiert sich in einer Organisation, die sich für die Bewahrung von Waldgebieten einsetzt.~n~n
Gesundheitlich geht es David S. gut. Außer einem geringfügig erhöhten Blutdruck hat er keinerlei Beschwerden. Er lebt alleine in einer geräumigen Dachgeschosswohnung."
</item>

<item david4>
/1 = "David S. arbeitet als Abteilungsleiter in einer großen Firma in Frankfurt am Main. Er beginnt seinen Arbeitstag meist gegen 8:30 Uhr und beendet ihn um 18 Uhr, freitags macht er etwas früher Schluss.~n~n
Aufgrund seiner beruflichen Erfahrung wurde er schon mehrfach gefragt, ob er sich vorstellen könnte, im Gemeinderat der örtlichen Kirchengemeinde mitzuarbeiten, in dem auch sein Vater tätig ist. Bislang hat er sich jedoch dagegen entschieden.~n~n
In seiner Freizeit treibt er zweimal die Woche Sport, liest viel und engagiert sich in einer Organisation, die sich für die Bewahrung von Waldgebieten einsetzt.~n~n
Gesundheitlich geht es David S. gut. Außer einem geringfügig erhöhten Blutdruck hat er keinerlei Beschwerden. Er lebt alleine in einer geräumigen Dachgeschosswohnung."
</item>

<text david_instr2>
/ items = ("Bitte lesen Sie die Informationen über die Person aufmerksam durch, um sich einen ersten Eindruck von der geschilderten Person zu bilden.")
/ fontstyle = ("Arial", 3%, true)
/ position = (50,20)
/ valign = bottom
/ size = (70%,15%)
</text>

<trial david>
/ stimulustimes = [0 = david, david_instr2, weiter]
/ validresponse = (weiter)
/ inputdevice = mouse
</trial>




<block david>
/ trials = [1=face_instr; 2=david_pic; 3=david]
</block>





********************************
********** PANAS ***********
********************************

<page panas>
^^Gefühle und Empfindungen
^^Dieser Fragebogen enthält eine Reihe von Wörtern, die unterschiedliche Gefühle und Empfindungen beschreiben.
Lesen Sie jedes Wort und wählen Sie dann mit der Maus in der darunter eingeblendeten Skala Ihre Antwort aus.
Geben Sie bitte an, wie sehr Sie sich gerade jetzt in diesem Moment in dieser Weise fühlen.
^^Benutzen Sie für Ihre Antwort die eingeblendete Skala von 1 = "sehr leicht oder gar nicht" bis 5 = "äußerst".
</page>

<item panas>
/ 1 ="aktiv"
/ 2 ="interessiert"
/ 3 ="freudig erregt"
/ 4  ="stark"
/ 5 ="angeregt"
/ 6 ="stolz"
/ 7 ="begeistert"
/ 8 ="wach"
/ 9 ="entschlossen"
/ 10 ="aufmerksam"
/ 11 ="bekümmert"
/ 12 ="verärgert"
/ 13 ="schuldig"
/ 14 ="erschrocken"
/ 15 ="feindselig"
/ 16 ="gereizt"
/ 17 ="beschämt"
/ 18 ="nervös"
/ 19 ="durcheinander"
/ 20 ="ängstlich"
</item>


<text panas_bg>
/ items = ("Ich fühle mich gerade jetzt in diesem Moment ...")
/ position = (50,30)
/ fontstyle =("Arial", 3.5%, false, true)
</text>


<text panas>
/ fontstyle =("Arial", 3.5%, true)
/ items = panas
/ position = (50%, 50%)
/ select = sequence
</text>

<likert panas>
/ anchors = [1="sehr leicht oder gar nicht"; 2="ein bisschen"; 3="einigermaßen"; 4="erheblich"; 5="äußerst"]
/ frames = [1 = panas, panas_bg]
/ anchorwidth = 15%
/ fontstyle = ("Arial", 1.5%, false)
/ mouse = true
/ numpoints = 5
/ position = (50%, 80%)
</likert>

<block panas>
/ preinstructions = (panas)
/ trials = [1-20 = panas]
</block>




********************************************
*******Reversed Correlation**********
********************************************
<page rating_task_davids>
^^In der nun folgenden visuellen Aufgabe werden Ihnen jeweils zwei Gesichter präsentiert. Bitte wählen Sie jeweils das Gesicht aus, welches Ihrer Meinung nach eher David S. ähnelt.
^^Vorherige Forschung hat ergeben, dass Studienteilnehmer relativ gut darin sind, zu entscheiden, welches Gesicht einer anderen zuvor nur kurz gesehenen Person ähnelt.
Um die Aufgabe schwieriger zu machen, sind beide Gesichter etwas verschwommen, als wenn Sie sie durch eine Milchglasscheibe betrachten würden.
Versuchen Sie trotzdem, dasjenige auszuwählen, das Sie für ähnlicher halten, als das andere.
Auch wenn sich die Gesichter teilweise sehr ähnlich sind und sich nur leicht unterscheiden, wird jedes Gesicht nur einmal im Laufe der Aufgabe gezeigt.
^^Sollten Sie Zweifel an Ihrer Entscheidung haben, antworten Sie einfach aus dem Bauch heraus.
^^Um Ihre visuelle Leistung in diesem Test stabil schätzen zu können, werden Sie 400 dieser Entscheidungen treffen.
Wir möchten Sie bitten, konzentriert und aufmerksam zu bleiben und gleichzeitig zügig zu antworten.
^^Um Ihnen dies zu erleichtern, haben wir die große Menge an Durchgängen in vier gleich große Blöcke aufgeteilt. Zwischen den Blöcken können Sie immer eine kurze Pause machen.
^^^^Bitte drücken Sie die Taste "E" für das linke Gesicht und die Taste "I" für das rechte Gesicht! 
</page>

<block facial_davids>
/ preinstructions=(rating_task_davids)
/ trials = [1-100 = noreplace(binary_face_davids); 101=interim1; 102-201 = noreplace(binary_face_davids); 202=interim2;
 203-302= noreplace(binary_face_davids); 303=interim3; 304-403= noreplace(binary_face_davids); 404=interimend]
</block>




<text zwischenblock1a>
/ position = (50,45)
/ items = ("Sie haben nun den ersten von vier Blöcken geschafft!")
/ numitems = 1
</text>

<text zwischenblock1b>
/ position = (50,80)
/ items = ("Weiter geht es durch Drücken der Enter-Taste!")
/ numitems = 1
</text>

<text zwischenblock2>
/ position = (50,45)
/ items = ("Sie haben nun den zweiten von vier Blöcken geschafft!")
/ numitems = 1
</text>

<text zwischenblock3>
/ position = (50,45)
/ items = ("Sie haben nun den dritten von vier Blöcken geschafft!")
/ numitems = 1
</text>

<text zwischenblockend>
/ position = (50,45)
/size = (900,200)
/ items = ("Sie haben nun diesen Teil der Untersuchung geschafft! ~nWenn Sie bereit sind drücken Sie bitte die Enter-Taste um fortzufahren.")
/ numitems = 1
</text>

<shape erase>
/ position = (50,10)
/ size = (80%,10%)
/ color = white
</shape>



<trial interim1>
/ stimulustimes = [1=erase, zwischenblock1a,zwischenblock1b]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>

<trial interim2>
/ stimulustimes = [1=erase, zwischenblock2,zwischenblock1b]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>

<trial interim3>
/ stimulustimes = [1=erase, zwischenblock3, zwischenblock1b]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>

<trial interimend>
/ stimulustimes = [1=erase, zwischenblockend]
/ font = ("Arial", -30, 700, 0, 49)
/ validresponse = (28)
</trial>



<text face_davids>
/ position = (50,10)
/ items = ("Welches Gesicht ähnelt David S. Ihrer Meinung nach eher?")
/ size = (80%,5%)
/ erase = false
</text>


<TRIAL binary_face_davids> 
/ stimulustimes= [1 = face_davids, stimuli0, stimuli1] 
/ validresponse = (18, 23)
</trial>


<picture stimuli0>
/ position = (25, 50)
/ numitems = 400
/ items = stimuli0
/ select = noreplace
</picture>

<picture stimuli1>
/ position = (75, 50)
/ numitems = 400
/ items = stimuli1
/ select = current(stimuli0)
</picture>



<item stimuli0>
/1 = "stimuli/warmth2014_m29-gaussian-15px_3_0.jpg"
/2 = "stimuli/warmth2014_m29-gaussian-15px_3_1.jpg"
/3 = "stimuli/warmth2014_m29-gaussian-15px_3_2.jpg"
/4 = "stimuli/warmth2014_m29-gaussian-15px_3_3.jpg"
/5 = "stimuli/warmth2014_m29-gaussian-15px_3_4.jpg"
/6 = "stimuli/warmth2014_m29-gaussian-15px_3_5.jpg"
/7 = "stimuli/warmth2014_m29-gaussian-15px_3_6.jpg"
/8 = "stimuli/warmth2014_m29-gaussian-15px_3_7.jpg"
/9 = "stimuli/warmth2014_m29-gaussian-15px_3_8.jpg"
/10 = "stimuli/warmth2014_m29-gaussian-15px_3_9.jpg"
/11 = "stimuli/warmth2014_m29-gaussian-15px_3_10.jpg"
/12 = "stimuli/warmth2014_m29-gaussian-15px_3_11.jpg"
/13 = "stimuli/warmth2014_m29-gaussian-15px_3_12.jpg"
/14 = "stimuli/warmth2014_m29-gaussian-15px_3_13.jpg"
/15 = "stimuli/warmth2014_m29-gaussian-15px_3_14.jpg"
/16 = "stimuli/warmth2014_m29-gaussian-15px_3_15.jpg"
/17 = "stimuli/warmth2014_m29-gaussian-15px_3_16.jpg"
/18 = "stimuli/warmth2014_m29-gaussian-15px_3_17.jpg"
/19 = "stimuli/warmth2014_m29-gaussian-15px_3_18.jpg"
/20 = "stimuli/warmth2014_m29-gaussian-15px_3_19.jpg"
/21 = "stimuli/warmth2014_m29-gaussian-15px_3_20.jpg"
/22 = "stimuli/warmth2014_m29-gaussian-15px_3_21.jpg"
/23 = "stimuli/warmth2014_m29-gaussian-15px_3_22.jpg"
/24 = "stimuli/warmth2014_m29-gaussian-15px_3_23.jpg"
/25 = "stimuli/warmth2014_m29-gaussian-15px_3_24.jpg"
/26 = "stimuli/warmth2014_m29-gaussian-15px_3_25.jpg"
/27 = "stimuli/warmth2014_m29-gaussian-15px_3_26.jpg"
/28 = "stimuli/warmth2014_m29-gaussian-15px_3_27.jpg"
/29 = "stimuli/warmth2014_m29-gaussian-15px_3_28.jpg"
/30 = "stimuli/warmth2014_m29-gaussian-15px_3_29.jpg"
/31 = "stimuli/warmth2014_m29-gaussian-15px_3_30.jpg"
/32 = "stimuli/warmth2014_m29-gaussian-15px_3_31.jpg"
/33 = "stimuli/warmth2014_m29-gaussian-15px_3_32.jpg"
/34 = "stimuli/warmth2014_m29-gaussian-15px_3_33.jpg"
/35 = "stimuli/warmth2014_m29-gaussian-15px_3_34.jpg"
/36 = "stimuli/warmth2014_m29-gaussian-15px_3_35.jpg"
/37 = "stimuli/warmth2014_m29-gaussian-15px_3_36.jpg"
/38 = "stimuli/warmth2014_m29-gaussian-15px_3_37.jpg"
/39 = "stimuli/warmth2014_m29-gaussian-15px_3_38.jpg"
/40 = "stimuli/warmth2014_m29-gaussian-15px_3_39.jpg"
/41 = "stimuli/warmth2014_m29-gaussian-15px_3_40.jpg"
/42 = "stimuli/warmth2014_m29-gaussian-15px_3_41.jpg"
/43 = "stimuli/warmth2014_m29-gaussian-15px_3_42.jpg"
/44 = "stimuli/warmth2014_m29-gaussian-15px_3_43.jpg"
/45 = "stimuli/warmth2014_m29-gaussian-15px_3_44.jpg"
/46 = "stimuli/warmth2014_m29-gaussian-15px_3_45.jpg"
/47 = "stimuli/warmth2014_m29-gaussian-15px_3_46.jpg"
/48 = "stimuli/warmth2014_m29-gaussian-15px_3_47.jpg"
/49 = "stimuli/warmth2014_m29-gaussian-15px_3_48.jpg"
/50 = "stimuli/warmth2014_m29-gaussian-15px_3_49.jpg"
/51 = "stimuli/warmth2014_m29-gaussian-15px_3_50.jpg"
/52 = "stimuli/warmth2014_m29-gaussian-15px_3_51.jpg"
/53 = "stimuli/warmth2014_m29-gaussian-15px_3_52.jpg"
/54 = "stimuli/warmth2014_m29-gaussian-15px_3_53.jpg"
/55 = "stimuli/warmth2014_m29-gaussian-15px_3_54.jpg"
/56 = "stimuli/warmth2014_m29-gaussian-15px_3_55.jpg"
/57 = "stimuli/warmth2014_m29-gaussian-15px_3_56.jpg"
/58 = "stimuli/warmth2014_m29-gaussian-15px_3_57.jpg"
/59 = "stimuli/warmth2014_m29-gaussian-15px_3_58.jpg"
/60 = "stimuli/warmth2014_m29-gaussian-15px_3_59.jpg"
/61 = "stimuli/warmth2014_m29-gaussian-15px_3_60.jpg"
/62 = "stimuli/warmth2014_m29-gaussian-15px_3_61.jpg"
/63 = "stimuli/warmth2014_m29-gaussian-15px_3_62.jpg"
/64 = "stimuli/warmth2014_m29-gaussian-15px_3_63.jpg"
/65 = "stimuli/warmth2014_m29-gaussian-15px_3_64.jpg"
/66 = "stimuli/warmth2014_m29-gaussian-15px_3_65.jpg"
/67 = "stimuli/warmth2014_m29-gaussian-15px_3_66.jpg"
/68 = "stimuli/warmth2014_m29-gaussian-15px_3_67.jpg"
/69 = "stimuli/warmth2014_m29-gaussian-15px_3_68.jpg"
/70 = "stimuli/warmth2014_m29-gaussian-15px_3_69.jpg"
/71 = "stimuli/warmth2014_m29-gaussian-15px_3_70.jpg"
/72 = "stimuli/warmth2014_m29-gaussian-15px_3_71.jpg"
/73 = "stimuli/warmth2014_m29-gaussian-15px_3_72.jpg"
/74 = "stimuli/warmth2014_m29-gaussian-15px_3_73.jpg"
/75 = "stimuli/warmth2014_m29-gaussian-15px_3_74.jpg"
/76 = "stimuli/warmth2014_m29-gaussian-15px_3_75.jpg"
/77 = "stimuli/warmth2014_m29-gaussian-15px_3_76.jpg"
/78 = "stimuli/warmth2014_m29-gaussian-15px_3_77.jpg"
/79 = "stimuli/warmth2014_m29-gaussian-15px_3_78.jpg"
/80 = "stimuli/warmth2014_m29-gaussian-15px_3_79.jpg"
/81 = "stimuli/warmth2014_m29-gaussian-15px_3_80.jpg"
/82 = "stimuli/warmth2014_m29-gaussian-15px_3_81.jpg"
/83 = "stimuli/warmth2014_m29-gaussian-15px_3_82.jpg"
/84 = "stimuli/warmth2014_m29-gaussian-15px_3_83.jpg"
/85 = "stimuli/warmth2014_m29-gaussian-15px_3_84.jpg"
/86 = "stimuli/warmth2014_m29-gaussian-15px_3_85.jpg"
/87 = "stimuli/warmth2014_m29-gaussian-15px_3_86.jpg"
/88 = "stimuli/warmth2014_m29-gaussian-15px_3_87.jpg"
/89 = "stimuli/warmth2014_m29-gaussian-15px_3_88.jpg"
/90 = "stimuli/warmth2014_m29-gaussian-15px_3_89.jpg"
/91 = "stimuli/warmth2014_m29-gaussian-15px_3_90.jpg"
/92 = "stimuli/warmth2014_m29-gaussian-15px_3_91.jpg"
/93 = "stimuli/warmth2014_m29-gaussian-15px_3_92.jpg"
/94 = "stimuli/warmth2014_m29-gaussian-15px_3_93.jpg"
/95 = "stimuli/warmth2014_m29-gaussian-15px_3_94.jpg"
/96 = "stimuli/warmth2014_m29-gaussian-15px_3_95.jpg"
/97 = "stimuli/warmth2014_m29-gaussian-15px_3_96.jpg"
/98 = "stimuli/warmth2014_m29-gaussian-15px_3_97.jpg"
/99 = "stimuli/warmth2014_m29-gaussian-15px_3_98.jpg"
/100 = "stimuli/warmth2014_m29-gaussian-15px_3_99.jpg"
/101 = "stimuli/warmth2014_m29-gaussian-15px_3_100.jpg"
/102 = "stimuli/warmth2014_m29-gaussian-15px_3_101.jpg"
/103 = "stimuli/warmth2014_m29-gaussian-15px_3_102.jpg"
/104 = "stimuli/warmth2014_m29-gaussian-15px_3_103.jpg"
/105 = "stimuli/warmth2014_m29-gaussian-15px_3_104.jpg"
/106 = "stimuli/warmth2014_m29-gaussian-15px_3_105.jpg"
/107 = "stimuli/warmth2014_m29-gaussian-15px_3_106.jpg"
/108 = "stimuli/warmth2014_m29-gaussian-15px_3_107.jpg"
/109 = "stimuli/warmth2014_m29-gaussian-15px_3_108.jpg"
/110 = "stimuli/warmth2014_m29-gaussian-15px_3_109.jpg"
/111 = "stimuli/warmth2014_m29-gaussian-15px_3_110.jpg"
/112 = "stimuli/warmth2014_m29-gaussian-15px_3_111.jpg"
/113 = "stimuli/warmth2014_m29-gaussian-15px_3_112.jpg"
/114 = "stimuli/warmth2014_m29-gaussian-15px_3_113.jpg"
/115 = "stimuli/warmth2014_m29-gaussian-15px_3_114.jpg"
/116 = "stimuli/warmth2014_m29-gaussian-15px_3_115.jpg"
/117 = "stimuli/warmth2014_m29-gaussian-15px_3_116.jpg"
/118 = "stimuli/warmth2014_m29-gaussian-15px_3_117.jpg"
/119 = "stimuli/warmth2014_m29-gaussian-15px_3_118.jpg"
/120 = "stimuli/warmth2014_m29-gaussian-15px_3_119.jpg"
/121 = "stimuli/warmth2014_m29-gaussian-15px_3_120.jpg"
/122 = "stimuli/warmth2014_m29-gaussian-15px_3_121.jpg"
/123 = "stimuli/warmth2014_m29-gaussian-15px_3_122.jpg"
/124 = "stimuli/warmth2014_m29-gaussian-15px_3_123.jpg"
/125 = "stimuli/warmth2014_m29-gaussian-15px_3_124.jpg"
/126 = "stimuli/warmth2014_m29-gaussian-15px_3_125.jpg"
/127 = "stimuli/warmth2014_m29-gaussian-15px_3_126.jpg"
/128 = "stimuli/warmth2014_m29-gaussian-15px_3_127.jpg"
/129 = "stimuli/warmth2014_m29-gaussian-15px_3_128.jpg"
/130 = "stimuli/warmth2014_m29-gaussian-15px_3_129.jpg"
/131 = "stimuli/warmth2014_m29-gaussian-15px_3_130.jpg"
/132 = "stimuli/warmth2014_m29-gaussian-15px_3_131.jpg"
/133 = "stimuli/warmth2014_m29-gaussian-15px_3_132.jpg"
/134 = "stimuli/warmth2014_m29-gaussian-15px_3_133.jpg"
/135 = "stimuli/warmth2014_m29-gaussian-15px_3_134.jpg"
/136 = "stimuli/warmth2014_m29-gaussian-15px_3_135.jpg"
/137 = "stimuli/warmth2014_m29-gaussian-15px_3_136.jpg"
/138 = "stimuli/warmth2014_m29-gaussian-15px_3_137.jpg"
/139 = "stimuli/warmth2014_m29-gaussian-15px_3_138.jpg"
/140 = "stimuli/warmth2014_m29-gaussian-15px_3_139.jpg"
/141 = "stimuli/warmth2014_m29-gaussian-15px_3_140.jpg"
/142 = "stimuli/warmth2014_m29-gaussian-15px_3_141.jpg"
/143 = "stimuli/warmth2014_m29-gaussian-15px_3_142.jpg"
/144 = "stimuli/warmth2014_m29-gaussian-15px_3_143.jpg"
/145 = "stimuli/warmth2014_m29-gaussian-15px_3_144.jpg"
/146 = "stimuli/warmth2014_m29-gaussian-15px_3_145.jpg"
/147 = "stimuli/warmth2014_m29-gaussian-15px_3_146.jpg"
/148 = "stimuli/warmth2014_m29-gaussian-15px_3_147.jpg"
/149 = "stimuli/warmth2014_m29-gaussian-15px_3_148.jpg"
/150 = "stimuli/warmth2014_m29-gaussian-15px_3_149.jpg"
/151 = "stimuli/warmth2014_m29-gaussian-15px_3_150.jpg"
/152 = "stimuli/warmth2014_m29-gaussian-15px_3_151.jpg"
/153 = "stimuli/warmth2014_m29-gaussian-15px_3_152.jpg"
/154 = "stimuli/warmth2014_m29-gaussian-15px_3_153.jpg"
/155 = "stimuli/warmth2014_m29-gaussian-15px_3_154.jpg"
/156 = "stimuli/warmth2014_m29-gaussian-15px_3_155.jpg"
/157 = "stimuli/warmth2014_m29-gaussian-15px_3_156.jpg"
/158 = "stimuli/warmth2014_m29-gaussian-15px_3_157.jpg"
/159 = "stimuli/warmth2014_m29-gaussian-15px_3_158.jpg"
/160 = "stimuli/warmth2014_m29-gaussian-15px_3_159.jpg"
/161 = "stimuli/warmth2014_m29-gaussian-15px_3_160.jpg"
/162 = "stimuli/warmth2014_m29-gaussian-15px_3_161.jpg"
/163 = "stimuli/warmth2014_m29-gaussian-15px_3_162.jpg"
/164 = "stimuli/warmth2014_m29-gaussian-15px_3_163.jpg"
/165 = "stimuli/warmth2014_m29-gaussian-15px_3_164.jpg"
/166 = "stimuli/warmth2014_m29-gaussian-15px_3_165.jpg"
/167 = "stimuli/warmth2014_m29-gaussian-15px_3_166.jpg"
/168 = "stimuli/warmth2014_m29-gaussian-15px_3_167.jpg"
/169 = "stimuli/warmth2014_m29-gaussian-15px_3_168.jpg"
/170 = "stimuli/warmth2014_m29-gaussian-15px_3_169.jpg"
/171 = "stimuli/warmth2014_m29-gaussian-15px_3_170.jpg"
/172 = "stimuli/warmth2014_m29-gaussian-15px_3_171.jpg"
/173 = "stimuli/warmth2014_m29-gaussian-15px_3_172.jpg"
/174 = "stimuli/warmth2014_m29-gaussian-15px_3_173.jpg"
/175 = "stimuli/warmth2014_m29-gaussian-15px_3_174.jpg"
/176 = "stimuli/warmth2014_m29-gaussian-15px_3_175.jpg"
/177 = "stimuli/warmth2014_m29-gaussian-15px_3_176.jpg"
/178 = "stimuli/warmth2014_m29-gaussian-15px_3_177.jpg"
/179 = "stimuli/warmth2014_m29-gaussian-15px_3_178.jpg"
/180 = "stimuli/warmth2014_m29-gaussian-15px_3_179.jpg"
/181 = "stimuli/warmth2014_m29-gaussian-15px_3_180.jpg"
/182 = "stimuli/warmth2014_m29-gaussian-15px_3_181.jpg"
/183 = "stimuli/warmth2014_m29-gaussian-15px_3_182.jpg"
/184 = "stimuli/warmth2014_m29-gaussian-15px_3_183.jpg"
/185 = "stimuli/warmth2014_m29-gaussian-15px_3_184.jpg"
/186 = "stimuli/warmth2014_m29-gaussian-15px_3_185.jpg"
/187 = "stimuli/warmth2014_m29-gaussian-15px_3_186.jpg"
/188 = "stimuli/warmth2014_m29-gaussian-15px_3_187.jpg"
/189 = "stimuli/warmth2014_m29-gaussian-15px_3_188.jpg"
/190 = "stimuli/warmth2014_m29-gaussian-15px_3_189.jpg"
/191 = "stimuli/warmth2014_m29-gaussian-15px_3_190.jpg"
/192 = "stimuli/warmth2014_m29-gaussian-15px_3_191.jpg"
/193 = "stimuli/warmth2014_m29-gaussian-15px_3_192.jpg"
/194 = "stimuli/warmth2014_m29-gaussian-15px_3_193.jpg"
/195 = "stimuli/warmth2014_m29-gaussian-15px_3_194.jpg"
/196 = "stimuli/warmth2014_m29-gaussian-15px_3_195.jpg"
/197 = "stimuli/warmth2014_m29-gaussian-15px_3_196.jpg"
/198 = "stimuli/warmth2014_m29-gaussian-15px_3_197.jpg"
/199 = "stimuli/warmth2014_m29-gaussian-15px_3_198.jpg"
/200 = "stimuli/warmth2014_m29-gaussian-15px_3_199.jpg"
/201 = "stimuli/warmth2014_m29-gaussian-15px_3_200.jpg"
/202 = "stimuli/warmth2014_m29-gaussian-15px_3_201.jpg"
/203 = "stimuli/warmth2014_m29-gaussian-15px_3_202.jpg"
/204 = "stimuli/warmth2014_m29-gaussian-15px_3_203.jpg"
/205 = "stimuli/warmth2014_m29-gaussian-15px_3_204.jpg"
/206 = "stimuli/warmth2014_m29-gaussian-15px_3_205.jpg"
/207 = "stimuli/warmth2014_m29-gaussian-15px_3_206.jpg"
/208 = "stimuli/warmth2014_m29-gaussian-15px_3_207.jpg"
/209 = "stimuli/warmth2014_m29-gaussian-15px_3_208.jpg"
/210 = "stimuli/warmth2014_m29-gaussian-15px_3_209.jpg"
/211 = "stimuli/warmth2014_m29-gaussian-15px_3_210.jpg"
/212 = "stimuli/warmth2014_m29-gaussian-15px_3_211.jpg"
/213 = "stimuli/warmth2014_m29-gaussian-15px_3_212.jpg"
/214 = "stimuli/warmth2014_m29-gaussian-15px_3_213.jpg"
/215 = "stimuli/warmth2014_m29-gaussian-15px_3_214.jpg"
/216 = "stimuli/warmth2014_m29-gaussian-15px_3_215.jpg"
/217 = "stimuli/warmth2014_m29-gaussian-15px_3_216.jpg"
/218 = "stimuli/warmth2014_m29-gaussian-15px_3_217.jpg"
/219 = "stimuli/warmth2014_m29-gaussian-15px_3_218.jpg"
/220 = "stimuli/warmth2014_m29-gaussian-15px_3_219.jpg"
/221 = "stimuli/warmth2014_m29-gaussian-15px_3_220.jpg"
/222 = "stimuli/warmth2014_m29-gaussian-15px_3_221.jpg"
/223 = "stimuli/warmth2014_m29-gaussian-15px_3_222.jpg"
/224 = "stimuli/warmth2014_m29-gaussian-15px_3_223.jpg"
/225 = "stimuli/warmth2014_m29-gaussian-15px_3_224.jpg"
/226 = "stimuli/warmth2014_m29-gaussian-15px_3_225.jpg"
/227 = "stimuli/warmth2014_m29-gaussian-15px_3_226.jpg"
/228 = "stimuli/warmth2014_m29-gaussian-15px_3_227.jpg"
/229 = "stimuli/warmth2014_m29-gaussian-15px_3_228.jpg"
/230 = "stimuli/warmth2014_m29-gaussian-15px_3_229.jpg"
/231 = "stimuli/warmth2014_m29-gaussian-15px_3_230.jpg"
/232 = "stimuli/warmth2014_m29-gaussian-15px_3_231.jpg"
/233 = "stimuli/warmth2014_m29-gaussian-15px_3_232.jpg"
/234 = "stimuli/warmth2014_m29-gaussian-15px_3_233.jpg"
/235 = "stimuli/warmth2014_m29-gaussian-15px_3_234.jpg"
/236 = "stimuli/warmth2014_m29-gaussian-15px_3_235.jpg"
/237 = "stimuli/warmth2014_m29-gaussian-15px_3_236.jpg"
/238 = "stimuli/warmth2014_m29-gaussian-15px_3_237.jpg"
/239 = "stimuli/warmth2014_m29-gaussian-15px_3_238.jpg"
/240 = "stimuli/warmth2014_m29-gaussian-15px_3_239.jpg"
/241 = "stimuli/warmth2014_m29-gaussian-15px_3_240.jpg"
/242 = "stimuli/warmth2014_m29-gaussian-15px_3_241.jpg"
/243 = "stimuli/warmth2014_m29-gaussian-15px_3_242.jpg"
/244 = "stimuli/warmth2014_m29-gaussian-15px_3_243.jpg"
/245 = "stimuli/warmth2014_m29-gaussian-15px_3_244.jpg"
/246 = "stimuli/warmth2014_m29-gaussian-15px_3_245.jpg"
/247 = "stimuli/warmth2014_m29-gaussian-15px_3_246.jpg"
/248 = "stimuli/warmth2014_m29-gaussian-15px_3_247.jpg"
/249 = "stimuli/warmth2014_m29-gaussian-15px_3_248.jpg"
/250 = "stimuli/warmth2014_m29-gaussian-15px_3_249.jpg"
/251 = "stimuli/warmth2014_m29-gaussian-15px_3_250.jpg"
/252 = "stimuli/warmth2014_m29-gaussian-15px_3_251.jpg"
/253 = "stimuli/warmth2014_m29-gaussian-15px_3_252.jpg"
/254 = "stimuli/warmth2014_m29-gaussian-15px_3_253.jpg"
/255 = "stimuli/warmth2014_m29-gaussian-15px_3_254.jpg"
/256 = "stimuli/warmth2014_m29-gaussian-15px_3_255.jpg"
/257 = "stimuli/warmth2014_m29-gaussian-15px_3_256.jpg"
/258 = "stimuli/warmth2014_m29-gaussian-15px_3_257.jpg"
/259 = "stimuli/warmth2014_m29-gaussian-15px_3_258.jpg"
/260 = "stimuli/warmth2014_m29-gaussian-15px_3_259.jpg"
/261 = "stimuli/warmth2014_m29-gaussian-15px_3_260.jpg"
/262 = "stimuli/warmth2014_m29-gaussian-15px_3_261.jpg"
/263 = "stimuli/warmth2014_m29-gaussian-15px_3_262.jpg"
/264 = "stimuli/warmth2014_m29-gaussian-15px_3_263.jpg"
/265 = "stimuli/warmth2014_m29-gaussian-15px_3_264.jpg"
/266 = "stimuli/warmth2014_m29-gaussian-15px_3_265.jpg"
/267 = "stimuli/warmth2014_m29-gaussian-15px_3_266.jpg"
/268 = "stimuli/warmth2014_m29-gaussian-15px_3_267.jpg"
/269 = "stimuli/warmth2014_m29-gaussian-15px_3_268.jpg"
/270 = "stimuli/warmth2014_m29-gaussian-15px_3_269.jpg"
/271 = "stimuli/warmth2014_m29-gaussian-15px_3_270.jpg"
/272 = "stimuli/warmth2014_m29-gaussian-15px_3_271.jpg"
/273 = "stimuli/warmth2014_m29-gaussian-15px_3_272.jpg"
/274 = "stimuli/warmth2014_m29-gaussian-15px_3_273.jpg"
/275 = "stimuli/warmth2014_m29-gaussian-15px_3_274.jpg"
/276 = "stimuli/warmth2014_m29-gaussian-15px_3_275.jpg"
/277 = "stimuli/warmth2014_m29-gaussian-15px_3_276.jpg"
/278 = "stimuli/warmth2014_m29-gaussian-15px_3_277.jpg"
/279 = "stimuli/warmth2014_m29-gaussian-15px_3_278.jpg"
/280 = "stimuli/warmth2014_m29-gaussian-15px_3_279.jpg"
/281 = "stimuli/warmth2014_m29-gaussian-15px_3_280.jpg"
/282 = "stimuli/warmth2014_m29-gaussian-15px_3_281.jpg"
/283 = "stimuli/warmth2014_m29-gaussian-15px_3_282.jpg"
/284 = "stimuli/warmth2014_m29-gaussian-15px_3_283.jpg"
/285 = "stimuli/warmth2014_m29-gaussian-15px_3_284.jpg"
/286 = "stimuli/warmth2014_m29-gaussian-15px_3_285.jpg"
/287 = "stimuli/warmth2014_m29-gaussian-15px_3_286.jpg"
/288 = "stimuli/warmth2014_m29-gaussian-15px_3_287.jpg"
/289 = "stimuli/warmth2014_m29-gaussian-15px_3_288.jpg"
/290 = "stimuli/warmth2014_m29-gaussian-15px_3_289.jpg"
/291 = "stimuli/warmth2014_m29-gaussian-15px_3_290.jpg"
/292 = "stimuli/warmth2014_m29-gaussian-15px_3_291.jpg"
/293 = "stimuli/warmth2014_m29-gaussian-15px_3_292.jpg"
/294 = "stimuli/warmth2014_m29-gaussian-15px_3_293.jpg"
/295 = "stimuli/warmth2014_m29-gaussian-15px_3_294.jpg"
/296 = "stimuli/warmth2014_m29-gaussian-15px_3_295.jpg"
/297 = "stimuli/warmth2014_m29-gaussian-15px_3_296.jpg"
/298 = "stimuli/warmth2014_m29-gaussian-15px_3_297.jpg"
/299 = "stimuli/warmth2014_m29-gaussian-15px_3_298.jpg"
/300 = "stimuli/warmth2014_m29-gaussian-15px_3_299.jpg"
/301 = "stimuli/warmth2014_m29-gaussian-15px_3_300.jpg"
/302 = "stimuli/warmth2014_m29-gaussian-15px_3_301.jpg"
/303 = "stimuli/warmth2014_m29-gaussian-15px_3_302.jpg"
/304 = "stimuli/warmth2014_m29-gaussian-15px_3_303.jpg"
/305 = "stimuli/warmth2014_m29-gaussian-15px_3_304.jpg"
/306 = "stimuli/warmth2014_m29-gaussian-15px_3_305.jpg"
/307 = "stimuli/warmth2014_m29-gaussian-15px_3_306.jpg"
/308 = "stimuli/warmth2014_m29-gaussian-15px_3_307.jpg"
/309 = "stimuli/warmth2014_m29-gaussian-15px_3_308.jpg"
/310 = "stimuli/warmth2014_m29-gaussian-15px_3_309.jpg"
/311 = "stimuli/warmth2014_m29-gaussian-15px_3_310.jpg"
/312 = "stimuli/warmth2014_m29-gaussian-15px_3_311.jpg"
/313 = "stimuli/warmth2014_m29-gaussian-15px_3_312.jpg"
/314 = "stimuli/warmth2014_m29-gaussian-15px_3_313.jpg"
/315 = "stimuli/warmth2014_m29-gaussian-15px_3_314.jpg"
/316 = "stimuli/warmth2014_m29-gaussian-15px_3_315.jpg"
/317 = "stimuli/warmth2014_m29-gaussian-15px_3_316.jpg"
/318 = "stimuli/warmth2014_m29-gaussian-15px_3_317.jpg"
/319 = "stimuli/warmth2014_m29-gaussian-15px_3_318.jpg"
/320 = "stimuli/warmth2014_m29-gaussian-15px_3_319.jpg"
/321 = "stimuli/warmth2014_m29-gaussian-15px_3_320.jpg"
/322 = "stimuli/warmth2014_m29-gaussian-15px_3_321.jpg"
/323 = "stimuli/warmth2014_m29-gaussian-15px_3_322.jpg"
/324 = "stimuli/warmth2014_m29-gaussian-15px_3_323.jpg"
/325 = "stimuli/warmth2014_m29-gaussian-15px_3_324.jpg"
/326 = "stimuli/warmth2014_m29-gaussian-15px_3_325.jpg"
/327 = "stimuli/warmth2014_m29-gaussian-15px_3_326.jpg"
/328 = "stimuli/warmth2014_m29-gaussian-15px_3_327.jpg"
/329 = "stimuli/warmth2014_m29-gaussian-15px_3_328.jpg"
/330 = "stimuli/warmth2014_m29-gaussian-15px_3_329.jpg"
/331 = "stimuli/warmth2014_m29-gaussian-15px_3_330.jpg"
/332 = "stimuli/warmth2014_m29-gaussian-15px_3_331.jpg"
/333 = "stimuli/warmth2014_m29-gaussian-15px_3_332.jpg"
/334 = "stimuli/warmth2014_m29-gaussian-15px_3_333.jpg"
/335 = "stimuli/warmth2014_m29-gaussian-15px_3_334.jpg"
/336 = "stimuli/warmth2014_m29-gaussian-15px_3_335.jpg"
/337 = "stimuli/warmth2014_m29-gaussian-15px_3_336.jpg"
/338 = "stimuli/warmth2014_m29-gaussian-15px_3_337.jpg"
/339 = "stimuli/warmth2014_m29-gaussian-15px_3_338.jpg"
/340 = "stimuli/warmth2014_m29-gaussian-15px_3_339.jpg"
/341 = "stimuli/warmth2014_m29-gaussian-15px_3_340.jpg"
/342 = "stimuli/warmth2014_m29-gaussian-15px_3_341.jpg"
/343 = "stimuli/warmth2014_m29-gaussian-15px_3_342.jpg"
/344 = "stimuli/warmth2014_m29-gaussian-15px_3_343.jpg"
/345 = "stimuli/warmth2014_m29-gaussian-15px_3_344.jpg"
/346 = "stimuli/warmth2014_m29-gaussian-15px_3_345.jpg"
/347 = "stimuli/warmth2014_m29-gaussian-15px_3_346.jpg"
/348 = "stimuli/warmth2014_m29-gaussian-15px_3_347.jpg"
/349 = "stimuli/warmth2014_m29-gaussian-15px_3_348.jpg"
/350 = "stimuli/warmth2014_m29-gaussian-15px_3_349.jpg"
/351 = "stimuli/warmth2014_m29-gaussian-15px_3_350.jpg"
/352 = "stimuli/warmth2014_m29-gaussian-15px_3_351.jpg"
/353 = "stimuli/warmth2014_m29-gaussian-15px_3_352.jpg"
/354 = "stimuli/warmth2014_m29-gaussian-15px_3_353.jpg"
/355 = "stimuli/warmth2014_m29-gaussian-15px_3_354.jpg"
/356 = "stimuli/warmth2014_m29-gaussian-15px_3_355.jpg"
/357 = "stimuli/warmth2014_m29-gaussian-15px_3_356.jpg"
/358 = "stimuli/warmth2014_m29-gaussian-15px_3_357.jpg"
/359 = "stimuli/warmth2014_m29-gaussian-15px_3_358.jpg"
/360 = "stimuli/warmth2014_m29-gaussian-15px_3_359.jpg"
/361 = "stimuli/warmth2014_m29-gaussian-15px_3_360.jpg"
/362 = "stimuli/warmth2014_m29-gaussian-15px_3_361.jpg"
/363 = "stimuli/warmth2014_m29-gaussian-15px_3_362.jpg"
/364 = "stimuli/warmth2014_m29-gaussian-15px_3_363.jpg"
/365 = "stimuli/warmth2014_m29-gaussian-15px_3_364.jpg"
/366 = "stimuli/warmth2014_m29-gaussian-15px_3_365.jpg"
/367 = "stimuli/warmth2014_m29-gaussian-15px_3_366.jpg"
/368 = "stimuli/warmth2014_m29-gaussian-15px_3_367.jpg"
/369 = "stimuli/warmth2014_m29-gaussian-15px_3_368.jpg"
/370 = "stimuli/warmth2014_m29-gaussian-15px_3_369.jpg"
/371 = "stimuli/warmth2014_m29-gaussian-15px_3_370.jpg"
/372 = "stimuli/warmth2014_m29-gaussian-15px_3_371.jpg"
/373 = "stimuli/warmth2014_m29-gaussian-15px_3_372.jpg"
/374 = "stimuli/warmth2014_m29-gaussian-15px_3_373.jpg"
/375 = "stimuli/warmth2014_m29-gaussian-15px_3_374.jpg"
/376 = "stimuli/warmth2014_m29-gaussian-15px_3_375.jpg"
/377 = "stimuli/warmth2014_m29-gaussian-15px_3_376.jpg"
/378 = "stimuli/warmth2014_m29-gaussian-15px_3_377.jpg"
/379 = "stimuli/warmth2014_m29-gaussian-15px_3_378.jpg"
/380 = "stimuli/warmth2014_m29-gaussian-15px_3_379.jpg"
/381 = "stimuli/warmth2014_m29-gaussian-15px_3_380.jpg"
/382 = "stimuli/warmth2014_m29-gaussian-15px_3_381.jpg"
/383 = "stimuli/warmth2014_m29-gaussian-15px_3_382.jpg"
/384 = "stimuli/warmth2014_m29-gaussian-15px_3_383.jpg"
/385 = "stimuli/warmth2014_m29-gaussian-15px_3_384.jpg"
/386 = "stimuli/warmth2014_m29-gaussian-15px_3_385.jpg"
/387 = "stimuli/warmth2014_m29-gaussian-15px_3_386.jpg"
/388 = "stimuli/warmth2014_m29-gaussian-15px_3_387.jpg"
/389 = "stimuli/warmth2014_m29-gaussian-15px_3_388.jpg"
/390 = "stimuli/warmth2014_m29-gaussian-15px_3_389.jpg"
/391 = "stimuli/warmth2014_m29-gaussian-15px_3_390.jpg"
/392 = "stimuli/warmth2014_m29-gaussian-15px_3_391.jpg"
/393 = "stimuli/warmth2014_m29-gaussian-15px_3_392.jpg"
/394 = "stimuli/warmth2014_m29-gaussian-15px_3_393.jpg"
/395 = "stimuli/warmth2014_m29-gaussian-15px_3_394.jpg"
/396 = "stimuli/warmth2014_m29-gaussian-15px_3_395.jpg"
/397 = "stimuli/warmth2014_m29-gaussian-15px_3_396.jpg"
/398 = "stimuli/warmth2014_m29-gaussian-15px_3_397.jpg"
/399 = "stimuli/warmth2014_m29-gaussian-15px_3_398.jpg"
/400 = "stimuli/warmth2014_m29-gaussian-15px_3_399.jpg"
</item>

<item stimuli1>
/1 = "stimuli/warmth2014_m29-gaussian-15px_3_0_neg.jpg"
/2 = "stimuli/warmth2014_m29-gaussian-15px_3_1_neg.jpg"
/3 = "stimuli/warmth2014_m29-gaussian-15px_3_2_neg.jpg"
/4 = "stimuli/warmth2014_m29-gaussian-15px_3_3_neg.jpg"
/5 = "stimuli/warmth2014_m29-gaussian-15px_3_4_neg.jpg"
/6 = "stimuli/warmth2014_m29-gaussian-15px_3_5_neg.jpg"
/7 = "stimuli/warmth2014_m29-gaussian-15px_3_6_neg.jpg"
/8 = "stimuli/warmth2014_m29-gaussian-15px_3_7_neg.jpg"
/9 = "stimuli/warmth2014_m29-gaussian-15px_3_8_neg.jpg"
/10 = "stimuli/warmth2014_m29-gaussian-15px_3_9_neg.jpg"
/11 = "stimuli/warmth2014_m29-gaussian-15px_3_10_neg.jpg"
/12 = "stimuli/warmth2014_m29-gaussian-15px_3_11_neg.jpg"
/13 = "stimuli/warmth2014_m29-gaussian-15px_3_12_neg.jpg"
/14 = "stimuli/warmth2014_m29-gaussian-15px_3_13_neg.jpg"
/15 = "stimuli/warmth2014_m29-gaussian-15px_3_14_neg.jpg"
/16 = "stimuli/warmth2014_m29-gaussian-15px_3_15_neg.jpg"
/17 = "stimuli/warmth2014_m29-gaussian-15px_3_16_neg.jpg"
/18 = "stimuli/warmth2014_m29-gaussian-15px_3_17_neg.jpg"
/19 = "stimuli/warmth2014_m29-gaussian-15px_3_18_neg.jpg"
/20 = "stimuli/warmth2014_m29-gaussian-15px_3_19_neg.jpg"
/21 = "stimuli/warmth2014_m29-gaussian-15px_3_20_neg.jpg"
/22 = "stimuli/warmth2014_m29-gaussian-15px_3_21_neg.jpg"
/23 = "stimuli/warmth2014_m29-gaussian-15px_3_22_neg.jpg"
/24 = "stimuli/warmth2014_m29-gaussian-15px_3_23_neg.jpg"
/25 = "stimuli/warmth2014_m29-gaussian-15px_3_24_neg.jpg"
/26 = "stimuli/warmth2014_m29-gaussian-15px_3_25_neg.jpg"
/27 = "stimuli/warmth2014_m29-gaussian-15px_3_26_neg.jpg"
/28 = "stimuli/warmth2014_m29-gaussian-15px_3_27_neg.jpg"
/29 = "stimuli/warmth2014_m29-gaussian-15px_3_28_neg.jpg"
/30 = "stimuli/warmth2014_m29-gaussian-15px_3_29_neg.jpg"
/31 = "stimuli/warmth2014_m29-gaussian-15px_3_30_neg.jpg"
/32 = "stimuli/warmth2014_m29-gaussian-15px_3_31_neg.jpg"
/33 = "stimuli/warmth2014_m29-gaussian-15px_3_32_neg.jpg"
/34 = "stimuli/warmth2014_m29-gaussian-15px_3_33_neg.jpg"
/35 = "stimuli/warmth2014_m29-gaussian-15px_3_34_neg.jpg"
/36 = "stimuli/warmth2014_m29-gaussian-15px_3_35_neg.jpg"
/37 = "stimuli/warmth2014_m29-gaussian-15px_3_36_neg.jpg"
/38 = "stimuli/warmth2014_m29-gaussian-15px_3_37_neg.jpg"
/39 = "stimuli/warmth2014_m29-gaussian-15px_3_38_neg.jpg"
/40 = "stimuli/warmth2014_m29-gaussian-15px_3_39_neg.jpg"
/41 = "stimuli/warmth2014_m29-gaussian-15px_3_40_neg.jpg"
/42 = "stimuli/warmth2014_m29-gaussian-15px_3_41_neg.jpg"
/43 = "stimuli/warmth2014_m29-gaussian-15px_3_42_neg.jpg"
/44 = "stimuli/warmth2014_m29-gaussian-15px_3_43_neg.jpg"
/45 = "stimuli/warmth2014_m29-gaussian-15px_3_44_neg.jpg"
/46 = "stimuli/warmth2014_m29-gaussian-15px_3_45_neg.jpg"
/47 = "stimuli/warmth2014_m29-gaussian-15px_3_46_neg.jpg"
/48 = "stimuli/warmth2014_m29-gaussian-15px_3_47_neg.jpg"
/49 = "stimuli/warmth2014_m29-gaussian-15px_3_48_neg.jpg"
/50 = "stimuli/warmth2014_m29-gaussian-15px_3_49_neg.jpg"
/51 = "stimuli/warmth2014_m29-gaussian-15px_3_50_neg.jpg"
/52 = "stimuli/warmth2014_m29-gaussian-15px_3_51_neg.jpg"
/53 = "stimuli/warmth2014_m29-gaussian-15px_3_52_neg.jpg"
/54 = "stimuli/warmth2014_m29-gaussian-15px_3_53_neg.jpg"
/55 = "stimuli/warmth2014_m29-gaussian-15px_3_54_neg.jpg"
/56 = "stimuli/warmth2014_m29-gaussian-15px_3_55_neg.jpg"
/57 = "stimuli/warmth2014_m29-gaussian-15px_3_56_neg.jpg"
/58 = "stimuli/warmth2014_m29-gaussian-15px_3_57_neg.jpg"
/59 = "stimuli/warmth2014_m29-gaussian-15px_3_58_neg.jpg"
/60 = "stimuli/warmth2014_m29-gaussian-15px_3_59_neg.jpg"
/61 = "stimuli/warmth2014_m29-gaussian-15px_3_60_neg.jpg"
/62 = "stimuli/warmth2014_m29-gaussian-15px_3_61_neg.jpg"
/63 = "stimuli/warmth2014_m29-gaussian-15px_3_62_neg.jpg"
/64 = "stimuli/warmth2014_m29-gaussian-15px_3_63_neg.jpg"
/65 = "stimuli/warmth2014_m29-gaussian-15px_3_64_neg.jpg"
/66 = "stimuli/warmth2014_m29-gaussian-15px_3_65_neg.jpg"
/67 = "stimuli/warmth2014_m29-gaussian-15px_3_66_neg.jpg"
/68 = "stimuli/warmth2014_m29-gaussian-15px_3_67_neg.jpg"
/69 = "stimuli/warmth2014_m29-gaussian-15px_3_68_neg.jpg"
/70 = "stimuli/warmth2014_m29-gaussian-15px_3_69_neg.jpg"
/71 = "stimuli/warmth2014_m29-gaussian-15px_3_70_neg.jpg"
/72 = "stimuli/warmth2014_m29-gaussian-15px_3_71_neg.jpg"
/73 = "stimuli/warmth2014_m29-gaussian-15px_3_72_neg.jpg"
/74 = "stimuli/warmth2014_m29-gaussian-15px_3_73_neg.jpg"
/75 = "stimuli/warmth2014_m29-gaussian-15px_3_74_neg.jpg"
/76 = "stimuli/warmth2014_m29-gaussian-15px_3_75_neg.jpg"
/77 = "stimuli/warmth2014_m29-gaussian-15px_3_76_neg.jpg"
/78 = "stimuli/warmth2014_m29-gaussian-15px_3_77_neg.jpg"
/79 = "stimuli/warmth2014_m29-gaussian-15px_3_78_neg.jpg"
/80 = "stimuli/warmth2014_m29-gaussian-15px_3_79_neg.jpg"
/81 = "stimuli/warmth2014_m29-gaussian-15px_3_80_neg.jpg"
/82 = "stimuli/warmth2014_m29-gaussian-15px_3_81_neg.jpg"
/83 = "stimuli/warmth2014_m29-gaussian-15px_3_82_neg.jpg"
/84 = "stimuli/warmth2014_m29-gaussian-15px_3_83_neg.jpg"
/85 = "stimuli/warmth2014_m29-gaussian-15px_3_84_neg.jpg"
/86 = "stimuli/warmth2014_m29-gaussian-15px_3_85_neg.jpg"
/87 = "stimuli/warmth2014_m29-gaussian-15px_3_86_neg.jpg"
/88 = "stimuli/warmth2014_m29-gaussian-15px_3_87_neg.jpg"
/89 = "stimuli/warmth2014_m29-gaussian-15px_3_88_neg.jpg"
/90 = "stimuli/warmth2014_m29-gaussian-15px_3_89_neg.jpg"
/91 = "stimuli/warmth2014_m29-gaussian-15px_3_90_neg.jpg"
/92 = "stimuli/warmth2014_m29-gaussian-15px_3_91_neg.jpg"
/93 = "stimuli/warmth2014_m29-gaussian-15px_3_92_neg.jpg"
/94 = "stimuli/warmth2014_m29-gaussian-15px_3_93_neg.jpg"
/95 = "stimuli/warmth2014_m29-gaussian-15px_3_94_neg.jpg"
/96 = "stimuli/warmth2014_m29-gaussian-15px_3_95_neg.jpg"
/97 = "stimuli/warmth2014_m29-gaussian-15px_3_96_neg.jpg"
/98 = "stimuli/warmth2014_m29-gaussian-15px_3_97_neg.jpg"
/99 = "stimuli/warmth2014_m29-gaussian-15px_3_98_neg.jpg"
/100 = "stimuli/warmth2014_m29-gaussian-15px_3_99_neg.jpg"
/101 = "stimuli/warmth2014_m29-gaussian-15px_3_100_neg.jpg"
/102 = "stimuli/warmth2014_m29-gaussian-15px_3_101_neg.jpg"
/103 = "stimuli/warmth2014_m29-gaussian-15px_3_102_neg.jpg"
/104 = "stimuli/warmth2014_m29-gaussian-15px_3_103_neg.jpg"
/105 = "stimuli/warmth2014_m29-gaussian-15px_3_104_neg.jpg"
/106 = "stimuli/warmth2014_m29-gaussian-15px_3_105_neg.jpg"
/107 = "stimuli/warmth2014_m29-gaussian-15px_3_106_neg.jpg"
/108 = "stimuli/warmth2014_m29-gaussian-15px_3_107_neg.jpg"
/109 = "stimuli/warmth2014_m29-gaussian-15px_3_108_neg.jpg"
/110 = "stimuli/warmth2014_m29-gaussian-15px_3_109_neg.jpg"
/111 = "stimuli/warmth2014_m29-gaussian-15px_3_110_neg.jpg"
/112 = "stimuli/warmth2014_m29-gaussian-15px_3_111_neg.jpg"
/113 = "stimuli/warmth2014_m29-gaussian-15px_3_112_neg.jpg"
/114 = "stimuli/warmth2014_m29-gaussian-15px_3_113_neg.jpg"
/115 = "stimuli/warmth2014_m29-gaussian-15px_3_114_neg.jpg"
/116 = "stimuli/warmth2014_m29-gaussian-15px_3_115_neg.jpg"
/117 = "stimuli/warmth2014_m29-gaussian-15px_3_116_neg.jpg"
/118 = "stimuli/warmth2014_m29-gaussian-15px_3_117_neg.jpg"
/119 = "stimuli/warmth2014_m29-gaussian-15px_3_118_neg.jpg"
/120 = "stimuli/warmth2014_m29-gaussian-15px_3_119_neg.jpg"
/121 = "stimuli/warmth2014_m29-gaussian-15px_3_120_neg.jpg"
/122 = "stimuli/warmth2014_m29-gaussian-15px_3_121_neg.jpg"
/123 = "stimuli/warmth2014_m29-gaussian-15px_3_122_neg.jpg"
/124 = "stimuli/warmth2014_m29-gaussian-15px_3_123_neg.jpg"
/125 = "stimuli/warmth2014_m29-gaussian-15px_3_124_neg.jpg"
/126 = "stimuli/warmth2014_m29-gaussian-15px_3_125_neg.jpg"
/127 = "stimuli/warmth2014_m29-gaussian-15px_3_126_neg.jpg"
/128 = "stimuli/warmth2014_m29-gaussian-15px_3_127_neg.jpg"
/129 = "stimuli/warmth2014_m29-gaussian-15px_3_128_neg.jpg"
/130 = "stimuli/warmth2014_m29-gaussian-15px_3_129_neg.jpg"
/131 = "stimuli/warmth2014_m29-gaussian-15px_3_130_neg.jpg"
/132 = "stimuli/warmth2014_m29-gaussian-15px_3_131_neg.jpg"
/133 = "stimuli/warmth2014_m29-gaussian-15px_3_132_neg.jpg"
/134 = "stimuli/warmth2014_m29-gaussian-15px_3_133_neg.jpg"
/135 = "stimuli/warmth2014_m29-gaussian-15px_3_134_neg.jpg"
/136 = "stimuli/warmth2014_m29-gaussian-15px_3_135_neg.jpg"
/137 = "stimuli/warmth2014_m29-gaussian-15px_3_136_neg.jpg"
/138 = "stimuli/warmth2014_m29-gaussian-15px_3_137_neg.jpg"
/139 = "stimuli/warmth2014_m29-gaussian-15px_3_138_neg.jpg"
/140 = "stimuli/warmth2014_m29-gaussian-15px_3_139_neg.jpg"
/141 = "stimuli/warmth2014_m29-gaussian-15px_3_140_neg.jpg"
/142 = "stimuli/warmth2014_m29-gaussian-15px_3_141_neg.jpg"
/143 = "stimuli/warmth2014_m29-gaussian-15px_3_142_neg.jpg"
/144 = "stimuli/warmth2014_m29-gaussian-15px_3_143_neg.jpg"
/145 = "stimuli/warmth2014_m29-gaussian-15px_3_144_neg.jpg"
/146 = "stimuli/warmth2014_m29-gaussian-15px_3_145_neg.jpg"
/147 = "stimuli/warmth2014_m29-gaussian-15px_3_146_neg.jpg"
/148 = "stimuli/warmth2014_m29-gaussian-15px_3_147_neg.jpg"
/149 = "stimuli/warmth2014_m29-gaussian-15px_3_148_neg.jpg"
/150 = "stimuli/warmth2014_m29-gaussian-15px_3_149_neg.jpg"
/151 = "stimuli/warmth2014_m29-gaussian-15px_3_150_neg.jpg"
/152 = "stimuli/warmth2014_m29-gaussian-15px_3_151_neg.jpg"
/153 = "stimuli/warmth2014_m29-gaussian-15px_3_152_neg.jpg"
/154 = "stimuli/warmth2014_m29-gaussian-15px_3_153_neg.jpg"
/155 = "stimuli/warmth2014_m29-gaussian-15px_3_154_neg.jpg"
/156 = "stimuli/warmth2014_m29-gaussian-15px_3_155_neg.jpg"
/157 = "stimuli/warmth2014_m29-gaussian-15px_3_156_neg.jpg"
/158 = "stimuli/warmth2014_m29-gaussian-15px_3_157_neg.jpg"
/159 = "stimuli/warmth2014_m29-gaussian-15px_3_158_neg.jpg"
/160 = "stimuli/warmth2014_m29-gaussian-15px_3_159_neg.jpg"
/161 = "stimuli/warmth2014_m29-gaussian-15px_3_160_neg.jpg"
/162 = "stimuli/warmth2014_m29-gaussian-15px_3_161_neg.jpg"
/163 = "stimuli/warmth2014_m29-gaussian-15px_3_162_neg.jpg"
/164 = "stimuli/warmth2014_m29-gaussian-15px_3_163_neg.jpg"
/165 = "stimuli/warmth2014_m29-gaussian-15px_3_164_neg.jpg"
/166 = "stimuli/warmth2014_m29-gaussian-15px_3_165_neg.jpg"
/167 = "stimuli/warmth2014_m29-gaussian-15px_3_166_neg.jpg"
/168 = "stimuli/warmth2014_m29-gaussian-15px_3_167_neg.jpg"
/169 = "stimuli/warmth2014_m29-gaussian-15px_3_168_neg.jpg"
/170 = "stimuli/warmth2014_m29-gaussian-15px_3_169_neg.jpg"
/171 = "stimuli/warmth2014_m29-gaussian-15px_3_170_neg.jpg"
/172 = "stimuli/warmth2014_m29-gaussian-15px_3_171_neg.jpg"
/173 = "stimuli/warmth2014_m29-gaussian-15px_3_172_neg.jpg"
/174 = "stimuli/warmth2014_m29-gaussian-15px_3_173_neg.jpg"
/175 = "stimuli/warmth2014_m29-gaussian-15px_3_174_neg.jpg"
/176 = "stimuli/warmth2014_m29-gaussian-15px_3_175_neg.jpg"
/177 = "stimuli/warmth2014_m29-gaussian-15px_3_176_neg.jpg"
/178 = "stimuli/warmth2014_m29-gaussian-15px_3_177_neg.jpg"
/179 = "stimuli/warmth2014_m29-gaussian-15px_3_178_neg.jpg"
/180 = "stimuli/warmth2014_m29-gaussian-15px_3_179_neg.jpg"
/181 = "stimuli/warmth2014_m29-gaussian-15px_3_180_neg.jpg"
/182 = "stimuli/warmth2014_m29-gaussian-15px_3_181_neg.jpg"
/183 = "stimuli/warmth2014_m29-gaussian-15px_3_182_neg.jpg"
/184 = "stimuli/warmth2014_m29-gaussian-15px_3_183_neg.jpg"
/185 = "stimuli/warmth2014_m29-gaussian-15px_3_184_neg.jpg"
/186 = "stimuli/warmth2014_m29-gaussian-15px_3_185_neg.jpg"
/187 = "stimuli/warmth2014_m29-gaussian-15px_3_186_neg.jpg"
/188 = "stimuli/warmth2014_m29-gaussian-15px_3_187_neg.jpg"
/189 = "stimuli/warmth2014_m29-gaussian-15px_3_188_neg.jpg"
/190 = "stimuli/warmth2014_m29-gaussian-15px_3_189_neg.jpg"
/191 = "stimuli/warmth2014_m29-gaussian-15px_3_190_neg.jpg"
/192 = "stimuli/warmth2014_m29-gaussian-15px_3_191_neg.jpg"
/193 = "stimuli/warmth2014_m29-gaussian-15px_3_192_neg.jpg"
/194 = "stimuli/warmth2014_m29-gaussian-15px_3_193_neg.jpg"
/195 = "stimuli/warmth2014_m29-gaussian-15px_3_194_neg.jpg"
/196 = "stimuli/warmth2014_m29-gaussian-15px_3_195_neg.jpg"
/197 = "stimuli/warmth2014_m29-gaussian-15px_3_196_neg.jpg"
/198 = "stimuli/warmth2014_m29-gaussian-15px_3_197_neg.jpg"
/199 = "stimuli/warmth2014_m29-gaussian-15px_3_198_neg.jpg"
/200 = "stimuli/warmth2014_m29-gaussian-15px_3_199_neg.jpg"
/201 = "stimuli/warmth2014_m29-gaussian-15px_3_200_neg.jpg"
/202 = "stimuli/warmth2014_m29-gaussian-15px_3_201_neg.jpg"
/203 = "stimuli/warmth2014_m29-gaussian-15px_3_202_neg.jpg"
/204 = "stimuli/warmth2014_m29-gaussian-15px_3_203_neg.jpg"
/205 = "stimuli/warmth2014_m29-gaussian-15px_3_204_neg.jpg"
/206 = "stimuli/warmth2014_m29-gaussian-15px_3_205_neg.jpg"
/207 = "stimuli/warmth2014_m29-gaussian-15px_3_206_neg.jpg"
/208 = "stimuli/warmth2014_m29-gaussian-15px_3_207_neg.jpg"
/209 = "stimuli/warmth2014_m29-gaussian-15px_3_208_neg.jpg"
/210 = "stimuli/warmth2014_m29-gaussian-15px_3_209_neg.jpg"
/211 = "stimuli/warmth2014_m29-gaussian-15px_3_210_neg.jpg"
/212 = "stimuli/warmth2014_m29-gaussian-15px_3_211_neg.jpg"
/213 = "stimuli/warmth2014_m29-gaussian-15px_3_212_neg.jpg"
/214 = "stimuli/warmth2014_m29-gaussian-15px_3_213_neg.jpg"
/215 = "stimuli/warmth2014_m29-gaussian-15px_3_214_neg.jpg"
/216 = "stimuli/warmth2014_m29-gaussian-15px_3_215_neg.jpg"
/217 = "stimuli/warmth2014_m29-gaussian-15px_3_216_neg.jpg"
/218 = "stimuli/warmth2014_m29-gaussian-15px_3_217_neg.jpg"
/219 = "stimuli/warmth2014_m29-gaussian-15px_3_218_neg.jpg"
/220 = "stimuli/warmth2014_m29-gaussian-15px_3_219_neg.jpg"
/221 = "stimuli/warmth2014_m29-gaussian-15px_3_220_neg.jpg"
/222 = "stimuli/warmth2014_m29-gaussian-15px_3_221_neg.jpg"
/223 = "stimuli/warmth2014_m29-gaussian-15px_3_222_neg.jpg"
/224 = "stimuli/warmth2014_m29-gaussian-15px_3_223_neg.jpg"
/225 = "stimuli/warmth2014_m29-gaussian-15px_3_224_neg.jpg"
/226 = "stimuli/warmth2014_m29-gaussian-15px_3_225_neg.jpg"
/227 = "stimuli/warmth2014_m29-gaussian-15px_3_226_neg.jpg"
/228 = "stimuli/warmth2014_m29-gaussian-15px_3_227_neg.jpg"
/229 = "stimuli/warmth2014_m29-gaussian-15px_3_228_neg.jpg"
/230 = "stimuli/warmth2014_m29-gaussian-15px_3_229_neg.jpg"
/231 = "stimuli/warmth2014_m29-gaussian-15px_3_230_neg.jpg"
/232 = "stimuli/warmth2014_m29-gaussian-15px_3_231_neg.jpg"
/233 = "stimuli/warmth2014_m29-gaussian-15px_3_232_neg.jpg"
/234 = "stimuli/warmth2014_m29-gaussian-15px_3_233_neg.jpg"
/235 = "stimuli/warmth2014_m29-gaussian-15px_3_234_neg.jpg"
/236 = "stimuli/warmth2014_m29-gaussian-15px_3_235_neg.jpg"
/237 = "stimuli/warmth2014_m29-gaussian-15px_3_236_neg.jpg"
/238 = "stimuli/warmth2014_m29-gaussian-15px_3_237_neg.jpg"
/239 = "stimuli/warmth2014_m29-gaussian-15px_3_238_neg.jpg"
/240 = "stimuli/warmth2014_m29-gaussian-15px_3_239_neg.jpg"
/241 = "stimuli/warmth2014_m29-gaussian-15px_3_240_neg.jpg"
/242 = "stimuli/warmth2014_m29-gaussian-15px_3_241_neg.jpg"
/243 = "stimuli/warmth2014_m29-gaussian-15px_3_242_neg.jpg"
/244 = "stimuli/warmth2014_m29-gaussian-15px_3_243_neg.jpg"
/245 = "stimuli/warmth2014_m29-gaussian-15px_3_244_neg.jpg"
/246 = "stimuli/warmth2014_m29-gaussian-15px_3_245_neg.jpg"
/247 = "stimuli/warmth2014_m29-gaussian-15px_3_246_neg.jpg"
/248 = "stimuli/warmth2014_m29-gaussian-15px_3_247_neg.jpg"
/249 = "stimuli/warmth2014_m29-gaussian-15px_3_248_neg.jpg"
/250 = "stimuli/warmth2014_m29-gaussian-15px_3_249_neg.jpg"
/251 = "stimuli/warmth2014_m29-gaussian-15px_3_250_neg.jpg"
/252 = "stimuli/warmth2014_m29-gaussian-15px_3_251_neg.jpg"
/253 = "stimuli/warmth2014_m29-gaussian-15px_3_252_neg.jpg"
/254 = "stimuli/warmth2014_m29-gaussian-15px_3_253_neg.jpg"
/255 = "stimuli/warmth2014_m29-gaussian-15px_3_254_neg.jpg"
/256 = "stimuli/warmth2014_m29-gaussian-15px_3_255_neg.jpg"
/257 = "stimuli/warmth2014_m29-gaussian-15px_3_256_neg.jpg"
/258 = "stimuli/warmth2014_m29-gaussian-15px_3_257_neg.jpg"
/259 = "stimuli/warmth2014_m29-gaussian-15px_3_258_neg.jpg"
/260 = "stimuli/warmth2014_m29-gaussian-15px_3_259_neg.jpg"
/261 = "stimuli/warmth2014_m29-gaussian-15px_3_260_neg.jpg"
/262 = "stimuli/warmth2014_m29-gaussian-15px_3_261_neg.jpg"
/263 = "stimuli/warmth2014_m29-gaussian-15px_3_262_neg.jpg"
/264 = "stimuli/warmth2014_m29-gaussian-15px_3_263_neg.jpg"
/265 = "stimuli/warmth2014_m29-gaussian-15px_3_264_neg.jpg"
/266 = "stimuli/warmth2014_m29-gaussian-15px_3_265_neg.jpg"
/267 = "stimuli/warmth2014_m29-gaussian-15px_3_266_neg.jpg"
/268 = "stimuli/warmth2014_m29-gaussian-15px_3_267_neg.jpg"
/269 = "stimuli/warmth2014_m29-gaussian-15px_3_268_neg.jpg"
/270 = "stimuli/warmth2014_m29-gaussian-15px_3_269_neg.jpg"
/271 = "stimuli/warmth2014_m29-gaussian-15px_3_270_neg.jpg"
/272 = "stimuli/warmth2014_m29-gaussian-15px_3_271_neg.jpg"
/273 = "stimuli/warmth2014_m29-gaussian-15px_3_272_neg.jpg"
/274 = "stimuli/warmth2014_m29-gaussian-15px_3_273_neg.jpg"
/275 = "stimuli/warmth2014_m29-gaussian-15px_3_274_neg.jpg"
/276 = "stimuli/warmth2014_m29-gaussian-15px_3_275_neg.jpg"
/277 = "stimuli/warmth2014_m29-gaussian-15px_3_276_neg.jpg"
/278 = "stimuli/warmth2014_m29-gaussian-15px_3_277_neg.jpg"
/279 = "stimuli/warmth2014_m29-gaussian-15px_3_278_neg.jpg"
/280 = "stimuli/warmth2014_m29-gaussian-15px_3_279_neg.jpg"
/281 = "stimuli/warmth2014_m29-gaussian-15px_3_280_neg.jpg"
/282 = "stimuli/warmth2014_m29-gaussian-15px_3_281_neg.jpg"
/283 = "stimuli/warmth2014_m29-gaussian-15px_3_282_neg.jpg"
/284 = "stimuli/warmth2014_m29-gaussian-15px_3_283_neg.jpg"
/285 = "stimuli/warmth2014_m29-gaussian-15px_3_284_neg.jpg"
/286 = "stimuli/warmth2014_m29-gaussian-15px_3_285_neg.jpg"
/287 = "stimuli/warmth2014_m29-gaussian-15px_3_286_neg.jpg"
/288 = "stimuli/warmth2014_m29-gaussian-15px_3_287_neg.jpg"
/289 = "stimuli/warmth2014_m29-gaussian-15px_3_288_neg.jpg"
/290 = "stimuli/warmth2014_m29-gaussian-15px_3_289_neg.jpg"
/291 = "stimuli/warmth2014_m29-gaussian-15px_3_290_neg.jpg"
/292 = "stimuli/warmth2014_m29-gaussian-15px_3_291_neg.jpg"
/293 = "stimuli/warmth2014_m29-gaussian-15px_3_292_neg.jpg"
/294 = "stimuli/warmth2014_m29-gaussian-15px_3_293_neg.jpg"
/295 = "stimuli/warmth2014_m29-gaussian-15px_3_294_neg.jpg"
/296 = "stimuli/warmth2014_m29-gaussian-15px_3_295_neg.jpg"
/297 = "stimuli/warmth2014_m29-gaussian-15px_3_296_neg.jpg"
/298 = "stimuli/warmth2014_m29-gaussian-15px_3_297_neg.jpg"
/299 = "stimuli/warmth2014_m29-gaussian-15px_3_298_neg.jpg"
/300 = "stimuli/warmth2014_m29-gaussian-15px_3_299_neg.jpg"
/301 = "stimuli/warmth2014_m29-gaussian-15px_3_300_neg.jpg"
/302 = "stimuli/warmth2014_m29-gaussian-15px_3_301_neg.jpg"
/303 = "stimuli/warmth2014_m29-gaussian-15px_3_302_neg.jpg"
/304 = "stimuli/warmth2014_m29-gaussian-15px_3_303_neg.jpg"
/305 = "stimuli/warmth2014_m29-gaussian-15px_3_304_neg.jpg"
/306 = "stimuli/warmth2014_m29-gaussian-15px_3_305_neg.jpg"
/307 = "stimuli/warmth2014_m29-gaussian-15px_3_306_neg.jpg"
/308 = "stimuli/warmth2014_m29-gaussian-15px_3_307_neg.jpg"
/309 = "stimuli/warmth2014_m29-gaussian-15px_3_308_neg.jpg"
/310 = "stimuli/warmth2014_m29-gaussian-15px_3_309_neg.jpg"
/311 = "stimuli/warmth2014_m29-gaussian-15px_3_310_neg.jpg"
/312 = "stimuli/warmth2014_m29-gaussian-15px_3_311_neg.jpg"
/313 = "stimuli/warmth2014_m29-gaussian-15px_3_312_neg.jpg"
/314 = "stimuli/warmth2014_m29-gaussian-15px_3_313_neg.jpg"
/315 = "stimuli/warmth2014_m29-gaussian-15px_3_314_neg.jpg"
/316 = "stimuli/warmth2014_m29-gaussian-15px_3_315_neg.jpg"
/317 = "stimuli/warmth2014_m29-gaussian-15px_3_316_neg.jpg"
/318 = "stimuli/warmth2014_m29-gaussian-15px_3_317_neg.jpg"
/319 = "stimuli/warmth2014_m29-gaussian-15px_3_318_neg.jpg"
/320 = "stimuli/warmth2014_m29-gaussian-15px_3_319_neg.jpg"
/321 = "stimuli/warmth2014_m29-gaussian-15px_3_320_neg.jpg"
/322 = "stimuli/warmth2014_m29-gaussian-15px_3_321_neg.jpg"
/323 = "stimuli/warmth2014_m29-gaussian-15px_3_322_neg.jpg"
/324 = "stimuli/warmth2014_m29-gaussian-15px_3_323_neg.jpg"
/325 = "stimuli/warmth2014_m29-gaussian-15px_3_324_neg.jpg"
/326 = "stimuli/warmth2014_m29-gaussian-15px_3_325_neg.jpg"
/327 = "stimuli/warmth2014_m29-gaussian-15px_3_326_neg.jpg"
/328 = "stimuli/warmth2014_m29-gaussian-15px_3_327_neg.jpg"
/329 = "stimuli/warmth2014_m29-gaussian-15px_3_328_neg.jpg"
/330 = "stimuli/warmth2014_m29-gaussian-15px_3_329_neg.jpg"
/331 = "stimuli/warmth2014_m29-gaussian-15px_3_330_neg.jpg"
/332 = "stimuli/warmth2014_m29-gaussian-15px_3_331_neg.jpg"
/333 = "stimuli/warmth2014_m29-gaussian-15px_3_332_neg.jpg"
/334 = "stimuli/warmth2014_m29-gaussian-15px_3_333_neg.jpg"
/335 = "stimuli/warmth2014_m29-gaussian-15px_3_334_neg.jpg"
/336 = "stimuli/warmth2014_m29-gaussian-15px_3_335_neg.jpg"
/337 = "stimuli/warmth2014_m29-gaussian-15px_3_336_neg.jpg"
/338 = "stimuli/warmth2014_m29-gaussian-15px_3_337_neg.jpg"
/339 = "stimuli/warmth2014_m29-gaussian-15px_3_338_neg.jpg"
/340 = "stimuli/warmth2014_m29-gaussian-15px_3_339_neg.jpg"
/341 = "stimuli/warmth2014_m29-gaussian-15px_3_340_neg.jpg"
/342 = "stimuli/warmth2014_m29-gaussian-15px_3_341_neg.jpg"
/343 = "stimuli/warmth2014_m29-gaussian-15px_3_342_neg.jpg"
/344 = "stimuli/warmth2014_m29-gaussian-15px_3_343_neg.jpg"
/345 = "stimuli/warmth2014_m29-gaussian-15px_3_344_neg.jpg"
/346 = "stimuli/warmth2014_m29-gaussian-15px_3_345_neg.jpg"
/347 = "stimuli/warmth2014_m29-gaussian-15px_3_346_neg.jpg"
/348 = "stimuli/warmth2014_m29-gaussian-15px_3_347_neg.jpg"
/349 = "stimuli/warmth2014_m29-gaussian-15px_3_348_neg.jpg"
/350 = "stimuli/warmth2014_m29-gaussian-15px_3_349_neg.jpg"
/351 = "stimuli/warmth2014_m29-gaussian-15px_3_350_neg.jpg"
/352 = "stimuli/warmth2014_m29-gaussian-15px_3_351_neg.jpg"
/353 = "stimuli/warmth2014_m29-gaussian-15px_3_352_neg.jpg"
/354 = "stimuli/warmth2014_m29-gaussian-15px_3_353_neg.jpg"
/355 = "stimuli/warmth2014_m29-gaussian-15px_3_354_neg.jpg"
/356 = "stimuli/warmth2014_m29-gaussian-15px_3_355_neg.jpg"
/357 = "stimuli/warmth2014_m29-gaussian-15px_3_356_neg.jpg"
/358 = "stimuli/warmth2014_m29-gaussian-15px_3_357_neg.jpg"
/359 = "stimuli/warmth2014_m29-gaussian-15px_3_358_neg.jpg"
/360 = "stimuli/warmth2014_m29-gaussian-15px_3_359_neg.jpg"
/361 = "stimuli/warmth2014_m29-gaussian-15px_3_360_neg.jpg"
/362 = "stimuli/warmth2014_m29-gaussian-15px_3_361_neg.jpg"
/363 = "stimuli/warmth2014_m29-gaussian-15px_3_362_neg.jpg"
/364 = "stimuli/warmth2014_m29-gaussian-15px_3_363_neg.jpg"
/365 = "stimuli/warmth2014_m29-gaussian-15px_3_364_neg.jpg"
/366 = "stimuli/warmth2014_m29-gaussian-15px_3_365_neg.jpg"
/367 = "stimuli/warmth2014_m29-gaussian-15px_3_366_neg.jpg"
/368 = "stimuli/warmth2014_m29-gaussian-15px_3_367_neg.jpg"
/369 = "stimuli/warmth2014_m29-gaussian-15px_3_368_neg.jpg"
/370 = "stimuli/warmth2014_m29-gaussian-15px_3_369_neg.jpg"
/371 = "stimuli/warmth2014_m29-gaussian-15px_3_370_neg.jpg"
/372 = "stimuli/warmth2014_m29-gaussian-15px_3_371_neg.jpg"
/373 = "stimuli/warmth2014_m29-gaussian-15px_3_372_neg.jpg"
/374 = "stimuli/warmth2014_m29-gaussian-15px_3_373_neg.jpg"
/375 = "stimuli/warmth2014_m29-gaussian-15px_3_374_neg.jpg"
/376 = "stimuli/warmth2014_m29-gaussian-15px_3_375_neg.jpg"
/377 = "stimuli/warmth2014_m29-gaussian-15px_3_376_neg.jpg"
/378 = "stimuli/warmth2014_m29-gaussian-15px_3_377_neg.jpg"
/379 = "stimuli/warmth2014_m29-gaussian-15px_3_378_neg.jpg"
/380 = "stimuli/warmth2014_m29-gaussian-15px_3_379_neg.jpg"
/381 = "stimuli/warmth2014_m29-gaussian-15px_3_380_neg.jpg"
/382 = "stimuli/warmth2014_m29-gaussian-15px_3_381_neg.jpg"
/383 = "stimuli/warmth2014_m29-gaussian-15px_3_382_neg.jpg"
/384 = "stimuli/warmth2014_m29-gaussian-15px_3_383_neg.jpg"
/385 = "stimuli/warmth2014_m29-gaussian-15px_3_384_neg.jpg"
/386 = "stimuli/warmth2014_m29-gaussian-15px_3_385_neg.jpg"
/387 = "stimuli/warmth2014_m29-gaussian-15px_3_386_neg.jpg"
/388 = "stimuli/warmth2014_m29-gaussian-15px_3_387_neg.jpg"
/389 = "stimuli/warmth2014_m29-gaussian-15px_3_388_neg.jpg"
/390 = "stimuli/warmth2014_m29-gaussian-15px_3_389_neg.jpg"
/391 = "stimuli/warmth2014_m29-gaussian-15px_3_390_neg.jpg"
/392 = "stimuli/warmth2014_m29-gaussian-15px_3_391_neg.jpg"
/393 = "stimuli/warmth2014_m29-gaussian-15px_3_392_neg.jpg"
/394 = "stimuli/warmth2014_m29-gaussian-15px_3_393_neg.jpg"
/395 = "stimuli/warmth2014_m29-gaussian-15px_3_394_neg.jpg"
/396 = "stimuli/warmth2014_m29-gaussian-15px_3_395_neg.jpg"
/397 = "stimuli/warmth2014_m29-gaussian-15px_3_396_neg.jpg"
/398 = "stimuli/warmth2014_m29-gaussian-15px_3_397_neg.jpg"
/399 = "stimuli/warmth2014_m29-gaussian-15px_3_398_neg.jpg"
/400 = "stimuli/warmth2014_m29-gaussian-15px_3_399_neg.jpg"
</item>

***********************************
***** Suspicion Probe 1
***********************************



<textbox suspicion1>
/ caption = "1. Beschreiben Sie in Ihren eigenen Worten, worum es Ihrer Meinung nach in dieser Studie geht."
/ multiline = true
/ required = false
/ textboxsize = (50%, 20%)
</textbox>

<textbox suspicion2>
/ caption = "2. Hatten Sie den Eindruck, dass bestimmte Reaktionen von Ihnen erwartet wurden? Wenn ja, welche?"
/ multiline = true
/ required = false
/ textboxsize = (50%, 15%)
</textbox>


<surveypage suspicion1>
/ caption = "Bevor es mit dem nächsten Teil weiter geht, möchten wir Sie um Feedback zu dem bisherigen Teil der Studie bitten. Wir möchten sicherstellen, dass der Aufbau der Studie stimmig ist und benötigen Ihre Rückmeldung, um uns bei der Verbesserung künftiger Studien zu helfen. Bitte beantworten Sie die folgenden Fragen so ehrlich wie möglich. Ihre Antworten sind äußerst wichtig für die wissenschaftliche Gültigkeit dieser Studie. Antworten Sie bitte so ausführlich, wie es Ihrer Meinung nach notwendig ist, um die jeweilige Frage vollständig zu beantworten."
/ questions = [1=suspicion1; 2=suspicion2]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<block suspicion1>
/ trials = [1=suspicion1]
</block>



***********************************
***** Explizites Rating David
***********************************

<page david_fragen>
^^Welchen ersten Eindruck haben Sie von David S. bekommen?
^^Es gibt bei den nun folgenden Aussagen keine richtigen und falschen Antworten, sondern nur Ihren persönlichen Eindruck, den Sie von David S. bekommen haben.
^^Bitte geben Sie jeweils auf der eingeblendeten Skala von 1 bis 7 an, wie sehr Sie der Aussage zustimmen.
</page>

<text david_fragen>
/items = david_fragen
/ fontstyle = ("Arial", 3%)
/ select = sequence
/ position = (50,50)
/ size = (70%, 30%)
</text>

<item david_fragen>
/1 = "David S. hilft gerne anderen, solange er weiß, dass es ihm zuerst gut geht."
/2 = "David S. kümmert sich zuerst um sich selbst und versucht dann, dafür zu sorgen, dass es anderen gut geht."
/3 = "Wenn es David S. nicht gut geht, kann man nicht von ihm erwarten, dass er versucht, sich um andere zu kümmern."
/4 = "David S. glaubt, jeder sollte für sich selbst sorgen."
/5 = "David S. achtet auf seinen eigenen Vorteil und kümmert sich nicht darum, was mit anderen passiert."
/6 = "David S. interessiert sich nur für seine Belange."
/7 = "Ich glaube, ich würde David S. mögen."
/8 = "Ich finde David S. sympathisch."
/9 = "Ich glaube, David S. ist berechnend."
/10 = "Ich glaube, David S. ist geizig."
/11 = "Ich glaube, David S. ist warmherzig."
/12 = "Ich glaube, David S. ist gerissen."
/13 = "Ich glaube, David S. ist vertrauenswürdig."
/14 = "Ich glaube, David S. ist rücksichtslos."
/15 = "Ich glaube, David S. ist skrupellos."
/16 = "Ich glaube, David S. ist ehrlich."
</item>



<likert david_fragen>
/ stimulustimes = [1=david_fragen]
/ anchors = [1="stimme überhaupt nicht zu"; 7="stimme voll und ganz zu"]
/ anchorwidth = 5%
/ numpoints = 7
/ fontstyle = ("Arial", 1.5%, false)
/ position = (50, 70)
/ mouse=true
</likert>

<block david_fragen>
/ preinstructions = (david_fragen)
/ trials = [1-16 = david_fragen]
/ postinstructions = (wsc_pre)
</block>




<page wsc_pre>
^^Da wir uns in dieser Studie für Ihre Erinnerungsleistung interessieren, folgt nun eine kurze Pause, bevor es mit dem letzten Teil der eigentlichen Studie weiter geht.
^^In dieser Zeit möchten wir Sie bitten, die folgende Wortstammergänzungsaufgabe zu bearbeiten.
^^Diese dient zur Erstellung von Untersuchungsmaterial für zukünftige Forschungsprojekte.
^^Bitte klicken Sie jetzt auf "Weiter" um mit der Wortstammergänzungsaufgabe zu beginnen.
</page>

******************************************************
********** Word Stem Completion **************
******************************************************

<text wsc>
/ fontstyle = ("Arial", 3.5%)
/ select = noreplace
/ items = wsc
</text>

<item wsc>
/1 = "Depo_________"
/2 = "Endl_________"
/3 = "Erm__________"
/4 = "Gask_________"
/5 = "Geno_________"
/6 = "Hol_________"
/7 = "Konz_________"
/8 = "Krem_________"
/9 = "Verga_________"
/10 = "Vern_________"
/11 = "Akte_________"
/12 = "Alte_________"
/13 = "Bewe_________"
/14 = "Einw_________"
/15 = "Empf_________"
/16 = "Erfa_________"
/17 = "Fort_________"
/18 = "Funk_________"
/19 = "Gymn_________"
/20 = "Hint_________"
/21 = "Kilo_________"
/22 = "Krei_________"
/23 = "Lieb_________"
/24 = "Mono_________"
/25 = "Nage_________"
/26 = "Pers_________"
/27 = "Rege_________"
/28 = "Rück_________"
/29 = "Stei_________"
/30 = "Zusa_________"
</item>



<openended wsc>
/ charlimit = 20
/ linelength = 30
/ multiline = false
/ position = (50,70)
/ stimulustimes = [0 = wsc]
/ posttrialpause = 250
/ buttonlabel = "Weiter"
</openended>

<htmlpage wsc>
/ file = "wsc_instr.html"
</htmlpage>

<block wsc>
/ onblockbegin = [instruct.width = 60%]
/ preinstructions = (wsc)
/ trials = [1-30=wsc]
/ onblockend = [instruct.width = 98%]
</block>



******************************************************
********** Manipulation Check *****************
******************************************************


<radiobuttons a>
/ caption = ""
/ options = ("David S. studiert in Mannheim Psychologie.", "David S. arbeitet in Köln als Versicherungsangestellter.","David S. arbeitet in Frankfurt an der Oder als Börsenmakler.","David S. arbeitet als Abteilungsleiter in Frankfurt am Main.")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons b>
/ caption = ""
/ options = ("Er arbeitet werktags von 9-19 Uhr.", "Er arbeitet nur samstags von 12-19 Uhr.","Er arbeitet jeden Tag von 8.30-18 Uhr und macht freitags früher Schluss.","Er arbeitet jeden Tag von 8.30-18 Uhr und macht dienstags früher Schluss.")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons c>
/ caption = ""
/ options = ("Sein Vater arbeitet in der örtlichen Kirchengemeinde.", "Sein Vater arbeitet in der örtlichen Synagoge.","Sein Vater arbeitet in der städtischen Kreisverwaltung als leitender Angestellter.","Sein Vater ist bereits berentet und arbeitet nebenbei als Zeitungsausträger.")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons d>
/ caption = ""
/ options = ("David S. lebt mit seinem Hund in einer kleinen Parterrewohnung.", "David S. wohnt alleine in einer großen Mietswohnung.","David S. lebt mit Frau und Kindern in einem Frankfurter Reihenhaus.","David S. wohnt alleine in einer Dachgeschosswohnung.")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons e>
/ caption = ""
/ options = ("David S. geht gerne schwimmen.", "David S. treibt viel Sport.","David S. schaut gerne Fernsehen.","David S. geht gerne spazieren.")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>

<radiobuttons f>
/ caption = ""
/ options = ("David S. engagiert sich für krebskranke Kinder.","David S. engagiert sich für überlebende KZ-Insassen.","David S. engagiert sich für die Bewahrung von Waldgebieten.", "David S. engagiert sich in einer Partei.")
/ optionvalues = ("1", "2","3","4")
</radiobuttons>


<surveypage mc_1>
/ caption = "Bitte erinnern Sie sich nun an den Text über David S. und wählen Sie aus den jeweils 4 Alternativen die Aussage über David S. aus, die Sie für richtig halten."
/ questions = [1=a; 2=b; 3=c; 4=d]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%, true)
/ itemfontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<surveypage mc_2>
/ caption = "Wählen Sie aus den jeweils 4 Alternativen die Aussage über David S. aus, die Sie für richtig halten."
/ questions = [1=e; 2=f]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%, true)
/ itemfontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>



<block mc>
/ trials = [1=mc_1; 2=mc_2]
</block>




**********************************************************************************************************************************************************************
**********************************************************************************************************************************************************************
	demog & religion
**********************************************************************************************************************************************************************
**********************************************************************************************************************************************************************
<page demog>
^^Vielen Dank! Hiermit ist der Hauptteil der Studie abgeschlossen.
^^Zum Schluss möchten wir Sie auf den folgenden Seiten bitten, einige Angaben zu Ihrer Person zu machen.
</page>


** demog.

<textbox age>
/ caption = "Alter:"
/ required = false
</textbox>

<radiobuttons sex>
/ caption = "Geschlecht:"
/ options = ("weiblich", "männlich")
/ optionvalues = ("1", "2")
/ orientation = horizontal
</radiobuttons>

<radiobuttons bildung>
/ caption = "Bildungsabschluss:"
/ options = ("Hauptschule", "Realschule", "Gymnasium", "Universität", "keiner")
/ optionvalues = ("1", "2", "3", "4", "0", "9")
/ other = "sonstiger:"
</radiobuttons>

<textbox fach>
/ caption = "Studienfach bzw. Beruf"
/ required = false
</textbox>

<radiobuttons migration>
/ caption = "Haben Sie einen Migrationshintergrund?"
/ options = ("ja", "nein")
/ optionvalues = ("1", "0")
/ orientation = horizontal
</radiobuttons>

<textbox migration2>
/ caption = "Falls ja, aus welchem Land?"
/ required = false
</textbox>

<radiobuttons religion>
/ caption = "Welcher Religion sind Sie angehörig?"
/ options = ("Chr. Katholisch", "Chr. Evangelisch", "Muslimisch", "Jüdisch", "keiner")
/ optionvalues = ("1", "2", "3", "4", "0", "9")
/ other = "andere:"
</radiobuttons>



<surveypage demog1>
/ caption = "Um beschreiben zu können, wer an dieser Studie teilgenommen hat, möchten wir Sie bitten, einige Angaben zu Ihrer Person zu machen."
/ questions = [1=age; 2=sex; 3=bildung; 4=fach]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%, true)
/ responsefontstyle = ("Arial", 1.5%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ txcolor = black
/ showquestionnumbers = false
</surveypage>

<surveypage demog2>
/ caption = ""
/ questions = [1=migration; 2=migration2; 3=religion]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%, true)
/ responsefontstyle = ("Arial", 1.5%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ txcolor = black
/ showquestionnumbers = false
</surveypage>

<block demog>
/ preinstructions = (demog)
/ trials = [1=demog1; 2=demog2]
</block>



<textbox comment>
/ caption = "Wenn Sie Anmerkungen zur Studie machen möchten, können Sie diese hier aufschreiben."
/ multiline = true
/ required = false
/ textboxsize = (30%, 20%)
</textbox>

<surveypage comment>
/ caption = "Vielen Dank für Ihre Teilnahme! ~nDie Studie ist jetzt beendet."
/ questions = [1=comment]
/ finishlabel = "Weiter"
/ nextlabel = "Weiter"
/ showbackbutton = false
/ fontstyle = ("Arial", 2%)
/ showpagenumbers = false
/ nextbuttonposition = (90,90) 
/ showquestionnumbers = false
</surveypage>

<block comment>
/ trials = [1=comment]
</block>

